### ISSUE TITLE
Transfer API shows fees but why no payments?

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#10374]
> [!IMPORTANT]  
> Edit: see ticket history for the previous request

There is currently no way for the Explorer to fetch all of the ledger entries related to a recurring transfer. THis makes it impossible to show on the Network Treasury page all of the occurences of a transfer.

# Tasks
- [ ] Update `ledger` table to correctly store transfer ID for recurring transfers. Currently it is `null`.
- [ ] Update `LedgerEntries` API to accept a `TransferId` which will narrow the ledger entries by the txId field.
  - [ ] Ensure change is in GRPC API
  - [ ] Ensure change is in REST API
  - [ ] Ensure change is in GraphQL API

**Comment by edd** [comment]
Example for a recurring transfer:

https://api.testnet.vega.rocks/graphql/#
```graphql
{
  transfer(id:"6655aa91eace8ac36ff59c84026d7982985d3b96a9728ab8ad0093892a0c7ca1") {
    fees {
      amount
      epoch
    }
    transfer {
      amount
      status
      kind {
        __typename
        ... on RecurringGovernanceTransfer {
          startEpoch
          endEpoch
        }
      }
    }
  }
}
```

Gives me:

```json
{
  "data": {
    "transfer": {
      "fees": [],
      "transfer": {
        "amount": "323000000",
        "status": "STATUS_DONE",
        "kind": {
          "__typename": "RecurringGovernanceTransfer",
          "startEpoch": 10088,
          "endEpoch": 10188
        }
      }
    }
  }
}
```

There is no way to know how many times this transfer actually occured. If the ledgerEntries query worked, I could use the start/end epoch dates like so:

```graphql
{
  ledgerEntries(filter: {
    FromAccountFilter: {
      partyIds: ["network"],
      accountTypes: ACCOUNT_TYPE_NETWORK_TREASURY

    }
    TransferId: "6655aa91eace8ac36ff59c84026d7982985d3b96a9728ab8ad0093892a0c7ca1"
  },
  dateRange: {
    start: "2023-11-15T12:17:52.34555Z",
    end: "2023-11-19T17:19:53.249505Z"
  }) {
    edges {
      node {
        assetId
        vegaTime
      }
    }
  }
}
```

but this query never returns

**Comment by edd** [comment]
An example of the query I'd like to do that still appears not to work:
```graphql
{
  ledgerEntries(filter: {
    ToAccountFilter: {
      partyIds: ["network"]
      accountTypes: [ACCOUNT_TYPE_NETWORK_TREASURY]
    },
    FromAccountFilter: {
      partyIds: ["network"]
      accountTypes: [ACCOUNT_TYPE_NETWORK_TREASURY]
    }
  }) {
    edges {
      node {
        assetId
        quantity
      }
    }
  }
}
```

**Comment by edd** [comment]
Ticket updated after discussion with @EVODelavega
