### ISSUE TITLE
[Feature]: AMM possible performance sticking points

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#10571]
This ticket is mostly a collection of things noted while implementing the AMM feature where I have thought "that _might_ cause of performance problems", but where I do not want to get bogged down addressing them _right now_ when its just speculation. But when we do come to performance testing this feature, it will be a nice to have this list:

- [ ] its thought that square root calculations will be slow, so we currently cache them but this may not be enough and some "trickery" might be needed.
- [ ] the parameters that define the curves for each side are `L, Pl, Pu`. The fair price calculations use terms such as `L*sqrt(Pu), L/sqrt(Pu), L*sqrt(Pl), L/sqrt(Pl)` which are constant. So we could pre-compute those and save some decimal operations.
- [ ] The orderbook matching happens in two halfs, a fake-uncross and then a real uncross. For a succesful order both halfs will do the same AMM calculations and produce the same orders. For a successful FOK order each half has a another step where volume-availble is calculated before doing the uncrossing, so in this case we will do the same calculations _four_ times. I can't see a reason why the FOK check needs to exist separately, so we could combine. Or do some complex caching in the amm engine.

## Specs
- [Link](xyz) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ]
- [ ]

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.
