### ISSUE TITLE
[EPIC]: Support Arbitrum bridge

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#10610]
Support for the Arbitrum bridge in the core.

## Green path

0. **Keep in mind we have to deduplicate chain events based on the hash**
   1. Convert all assets to be associated to the configured ethereum chain (using chain ID).
   2. Hash with Chain ID, if seen, dedup, if not seen, hash without chain ID, if seen dedup, if not, track event hash with with chain ID.
3. Add RPC config to enable arbitrum ETHClient.
4. Support in governance
   2. add chain ID to governance payload
   3. validation of asset with bridge based on chain ID
   5. add asset to asset pool and banking
   6. on enactment, emit signature that tells the bridge it shall allow the use of asset (support multiple chain ID)
   7. enable asset in collateral engine (support multiple chain ID)
4. Support deposit & withdraw
   1. Support chain ID in chain event (resolved from asset ID to chain ID)
   2. Validation using the correct ETHClient (ensure use of the arbitrum one)
   3. Finish deposit
   5. Withdrawal: emit signatures that are slightly modified: ethbridge = old signatures, arbitrum = new signatures. _to be refined_
4. Validation package (**To refined**, no ticket associated yet)
   1. Add and remove validators: `add_signer` / `remove_signer`
   2. Question: impact on rewards if bridge incorrectly setup ? Option: If one is not correctly setup -> no payment.
6. Proposal to update an asset
7. Support in API
   1. Add chain ID were needed (bundles, etc).

### Additional links
- Spec issue: https://github.com/vegaprotocol/specs/issues/2143
- Support in STs: https://github.com/vegaprotocol/system-tests/pull/3424
- Support in Capsule: https://github.com/vegaprotocol/vegacapsule/pull/432

```[tasklist]
### Tasks
- [ ] https://github.com/vegaprotocol/vega/issues/10612
- [ ] https://github.com/vegaprotocol/vega/issues/10624
- [ ] https://github.com/vegaprotocol/vega/issues/10623
- [ ] https://github.com/vegaprotocol/vega/issues/10717
- [ ] https://github.com/vegaprotocol/vega/issues/10854
- [ ] https://github.com/vegaprotocol/vega/issues/10853
- [ ] https://github.com/vegaprotocol/vega/issues/10821
- [ ] https://github.com/vegaprotocol/vega/issues/10870
```
