### ISSUE TITLE
[Feature]: vAMM integration test coverage

### ISSUE THREAD

**Issue by EVODelavega** [vegaprotocol/vega#10719]
# Feature Overview

Add coverage for vAMM AC's to the integration test suite

## Tasks
The full list of AC's:

- [x] https://github.com/vegaprotocol/core-test-coverage/issues/942
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/943
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/944
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/945
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/946
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/947
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/948
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/949
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/950
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/951
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/952
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/953
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/954
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/955
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/956
- [ ] https://github.com/vegaprotocol/core-test-coverage/issues/957
- [ ] https://github.com/vegaprotocol/core-test-coverage/issues/958
- [ ] https://github.com/vegaprotocol/core-test-coverage/issues/959
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/960
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/961
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/962
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/963
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/964
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/965
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/966
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/967
- [ ] https://github.com/vegaprotocol/core-test-coverage/issues/1001
- [ ] https://github.com/vegaprotocol/core-test-coverage/issues/1002
- [ ] https://github.com/vegaprotocol/core-test-coverage/issues/1003
- [ ] https://github.com/vegaprotocol/core-test-coverage/issues/1004
- [x] https://github.com/vegaprotocol/core-test-coverage/issues/1005

AC's listed here: https://github.com/vegaprotocol/specs/pull/2019/files#diff-edd2775de0d11367c32ce49024ef256476541d861a198a408cef25b79efee967R244
