### ISSUE TITLE
[Feature]: AMM pool logic missing cases

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#10733]
# Feature Overview

There are three things missing from the pool logic that manages a AMM's position and fair-price given its curve definition. We need to be sure we handle the following:
- [x] One-sided curves, for the case where `lowerBound` or `upperBound` is not provided
- [x] An incoming order that will change the sign of an AMM's position, currently it will only execute a trade that pushes it's position to 0. We need to then consider the any volume on the _other_ curve at this point.
- [x] Incoming order that pushing multiple pool's over their bounds, where each pool's boundaries are not alligned. As per the spec we need to execute these trades in stages up to each pool's boundary.

## Specs
- [Link](xyz) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ]
- [ ]

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.
