### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#11054]
# Feature Overview

**In order to** improve the current games functionality
**We will** look into these hopefully "quick fixes"
**So that** people find the games more engaging

## Tasks

Below is a list of suggested improvements based on a few week's experience and feedback we've had from users. 

Suggest we review all of these and decide which to take forward if any.

- [ ] Add a `runningVolumeRequirement` so that in addition to the notional requirement reward creators can ensure that in order to qualify for a reward users must be actively trading and not just sitting on positions
- [ ] Adjust the `relativeReturn` reward type so that instead of disregarding any key with a loss we rank ALL eligible keys in terms of P&L and reward them.  This would allow the game to account for the situation where the market turns and everyone is losing, but some are losing "better" than others.
  - [ ] For a pro rata game this would mean rewarding all eligible keys some amount
  - [ ] For a ranked game this would mean that keys in loss can still be in the ranking table
- [ ] Other?

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.

**Comment by barnabee** [comment]
Based on what I've seen in Discord chat plus observing the wild variation in number of eligible/rewarded teams because of the positive P&L requirement, I think these would be welcome changes.

It'd also be good to expose the metrics and/or the raw data counters that go into them live or at least in regularly updating snapshots via APIs so that a leaderboard can be produced that updates during the epoch. This would also help users understand the how/why of reward distributions by the prorotocol at epoch end.

**Comment by JonRay15** [comment]
Added that secone part here: https://github.com/vegaprotocol/vega/issues/11056

Since it is a quite different task to the other stuff listed above

**Comment by JonRay15** [comment]
I think realized PnL might be a bit more intuitive than having a running volume requirement because 

1. That running vol requirement feels a bit forced, it is more organic to say "i need to lock in X profit this epoch for it to count" than "I need X profit overall but need to make sure I've done Y running volume for it to count" 
2. Plus _currently_ I dont think we can expose that running volume during the epoch so until we have that available it will be a bit of a guessing game whether you have hit it or not.
3. Its easier as a trader to keep track of your realized PnL through the day ... you just need to know what it was at the end of the last epoch and what it is right now and you know what you've managed
