### ISSUE TITLE
[Feature]: Make relative return reward include losses

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#11114]
# Feature Overview

**In order to** improve the current games functionality
**We will** look into these hopefully "quick fixes"
**So that** people find the games more engaging

## Tasks

- [ ] Adjust the `relativeReturn` reward type so that instead of disregarding any key with a loss we rank ALL eligible keys in terms of P&L and reward them.  This would allow the game to account for the situation where the market turns and everyone is losing, but some are losing "better" than others.
  - [ ] For a pro rata game this would mean rewarding all eligible keys some amount
  - [ ] For a ranked game this would mean that keys in loss can still be in the ranking table
- [ ] Other?

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.
