### ISSUE TITLE
[Feature]: Make external views on EVM bridge extensible to multiple bridges

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#11138]
# Feature Overview

**In order to** ensure we do not shoot ourselves in the foot
**We will** make all external types related to the second bridge lists of those types
**So that** if we implement another EVM bridge in the future there is less chance of having awkward incompatibilites

Currently the Arbitrum bridge feature has been written with the assumption we will have 1 new bridge and this is fine internally when we don't really know what the future holds. 

Despite this it would make sense for all _external_ types to be such they _could_ easily extend to multiple EVM bridges so that there are fewer breaking changes that we might need to do if we implement another bridge.

For example we should:

- [ ] Change the single network parameter from a single `EVMChainConfig`  -> `listof(EMVChainConfig)` like we have for L2 data sources
- [ ] Change the config file RPC endpoint for the second bridge to be a `listof(RPCEndpoint+ChainID)` like we have for L2 data sources
- [ ] Change the snapshot payloads for the new bridge states to be `listof(bridge-states)` so that there is less snapshot migratiion needed later

## Specs
- [Link](xyz) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ]
- [ ]

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.
