### ISSUE TITLE
Add an 'UPGRADING.md' migrate from 0.53 -> 0.XX.x (mainnet releases)

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5487]
https://github.com/vegaprotocol/documentation/pull/94 added a node operator section to the documentation site. This is a good solution, but some people would prefer that the documentation is kept in the same place as the code. To address this, we're proposing to add a markdown file containing instructions. This will then be used as the source for the docs update ([see current version here](https://github.com/vegaprotocol/documentation/tree/main/docs/node-operators))

# Tasks
- [ ] Create UPGRADING file
- [ ] Starting with the current release to the next one, start documenting the process of how a validator would upgrade from a given tag to another
- [ ] update docs now tendermint is now part of the core

# Notes
Exactly which version needs an upgrade guide to the next is not defined in this ticket. Presumably it's anything with changes that break configuration. I'll leave it to the team to decide.
