### ISSUE TITLE
Address spec changes to multisig-score

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#5490]
# Feature Overview

Spec change: https://github.com/vegaprotocol/specs-internal/pull/1126
Slack conversation: https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1655714422071649

# Tasks
Ensure the below happens
- [ ] when node Bob is demoted from Tendermint -> erstaz, and Alice is promoted from Ersatz -> Tendermint, Alice is the only node that should have a 0 multisig score until they have both removed Bob and added themselves onto the contract. Every other TM node should have a multisig score of 1
- [ ] If a network parameter changes that will cause a node to be demoted, then all the remaining tendermint validators will get a multisig score of zero until the demoted validator is removed from the contract by any of the validators

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by wwestgarth** [comment]
No longer needed as the spec changed back again.
