### ISSUE TITLE
Generate JSON documentation

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#5670]
With the following PR: https://github.com/vegaprotocol/vega/pull/5667 the protobufs definitions are being imported in the core repo.

In order to limit cluttering the repo, we stopped generating json definitions and swagger. However this is still needed by the docs team to generate the website.

## Tasks
- [ ] add a step in the pipeline to generate all json and swagger
- [ ] Create a new repository dedicated to the documentation codegen
- [ ] On merge to develop, push all update json and swagger on the repo

**Comment by edd** [comment]
To add some more context:
https://github.com/vegaprotocol/documentation is the documentation repo. We use https://docusaurus.io/ to generate the documentation. [Here you can see the plugins we use to generate API documentation](https://github.com/vegaprotocol/documentation#docusaurus-plugins) from protobufs, GraphQL & REST, and the files they need to do it.

[wip]

**Comment by edd** [comment]
Also note: the generated swagger files *do not contain the correct base paths* for any api servers (https://swagger.io/docs/specification/api-host-and-base-path/). This is why the URLs are not correct on https://github.com/vegaprotocol/docs (old docs) or https://github.com/vegaprotocol/documentation (new docs)

**Comment by mkjmdski** [comment]
List of steps for automation:
1. vega repo on each commit to develop branch run -> scripts/generate_json.sh
2. generated artifacts are going to be push to vegaprotocol/documentation as a new branch in newly created `specs` directory
3. run `scripts/build.sh` on that documentation repo and open pull request with generated html
4. open a pull request
5. once all checks are passed merge a pull request

**Comment by jeremyletang** [comment]
> List of steps for automation:
> 
>     1. vega repo on each new tag run -> scripts/generate_json.sh
> 
>     2. generated artifacts are going to be push to vegaprotocol/documentation as a new branch in newly created `specs` directory in the tag name subdirectory
> 
>     3. run `scripts/build.sh` on that documentation repo and open pull request with generated html
> 
>     4. open a pull request
> 
>     5. once all checks are passed merge a pull request

if / once this get merged: https://github.com/vegaprotocol/vega/pull/5856, step 1 will need to change and be replaced with: `make proto_docs`.

Other steps might be impacted as the PR is also changing the layout of generated code, but I expect these changes  to be minimals.

**Comment by mkjmdski** [comment]
related slack link: https://vegaprotocol.slack.com/archives/CD4AKTFQT/p1660223354271599

**Comment by mkjmdski** [comment]
Install:
* https://github.com/bufbuild/buf
* https://github.com/golang/protobuf
