### ISSUE TITLE
GraphQL: updateAsset not implemented

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5699]
[REST has it](https://github.com/vegaprotocol/protos/blob/c2c2c20d06bc2e8b03ec3f26b1ae093610efcfd8/swagger/vega/api/v1/core.swagger.json#L4049-L4052). GRPC has it. But [not GraphQL](https://github.com/vegaprotocol/data-node/blob/develop/gateway/graphql/schema.graphql#L2487-L2536).

# Tasks
- [ ] Add `updateAsset` to `ProposalChange` type
- [ ] Add `UpdateAsset` type
- [ ] Add bindings to GraphQL gateway
