### ISSUE TITLE
Breakdown of liquidity provision, pegged and Natural orders in market Depth API

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vega#5701]
# Feature Overview

**In order to** communicate the nature of the order book
**We will** include an optional breakdown of the type of volume at each price level
**So that** it can be displayed to the user what type of orders are in the book

In this image the cumulative volume column of the order book component includes two mini visualisations. one to show the total cumulative volume, another to show the subset of that that is made up of liquidity provisions orders.

<img width="2095" alt="Screenshot 2022-04-27 at 12 19 42" src="https://user-images.githubusercontent.com/13255539/165507190-19be8c97-ea7f-4dfe-96a8-3c1ad20c6ab2.png">

There is an existing liquidity provisions GraphQL api, but it does not return current price level (only the peged references and does not have a subscription)

```GraphQL
{
	markets{
    liquidityProvisions{
      buys{
        order{
          peggedOrder{
            offset
            reference
          }
        }
        liquidityOrder{
          offset
          reference
          proportion
        }
      }
    }
  }
}
```

I do not know if it is best to integrate this with the market Depth API or create a new one and merge them on the client. please update ticket description as appropriate.

Ideally in an auction we'd still show the liquidity provisions (where they can be shown, i.e.g there is a bested/ask that isn't a peg), however this may need more discussion and could be out of scope of this ticket.

## Specs
none

# Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios. Ideally, tasks would reflect the issues/pull requests likely to be created when developing the feature. 
- [ ] Discuss with FE team
- [ ] make a decision about auctions
- [ ] implement API
- [ ] spike the UI
- [ ] feedback from UI teams

# Acceptance Criteria
A list of criteria (aim for 3!) that have to be met for this feature to be accepted as 'done' by the product owner.

- on the market Depth API It is possible to request a breakdown of the order types for each level
- there is a sum of volume by type (liquidity, pegged, limit)
- there is a subscription of this data 
- Auction mode is dealt with one way or another

Acceptance Criteria and Feature Test Scenarios can, in some cases, be closely related. If acceptance criteria become fully covered by feature test scenarios they can be removed leaving on acceptance criteria that can't be directly or fully proven with tests.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
Liquidity is going to change with SLA - once implemented we can revisit improvements
