### ISSUE TITLE
Trades by price in given time period

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vega#5702]
# Feature Overview
<img width="1069" alt="Screenshot 2022-04-27 at 11 37 24" src="https://user-images.githubusercontent.com/13255539/165500266-52800d1c-6fc9-46ad-ba11-7f2dd4897b00.png">
This shows a the sum of orders that have traded at each price within a given time period.
This helps a user see not just where the orders are but the levels where orders have traded (price often moves due to canceling/moving of orders as well as when order are matched).

**In order to** see where orders have matched
**We will** create an api
**So that** users and front ends can summarise at what prices trades have happened.

Note: there is already a cronilogical list of trades at
```GraphQL
{
  markets{
    trades{
      xxx
    }
  }
}
```
This is a request to have the information returned by price level within a time period instead.

In the mock up the trades summary is shown along side the order book that comes from

```GraphQL
{
  markets{
    depth{
      xxx
    }
  }
}
```
and subscription `MarketDepthUpdate`
so there is some value as perhaps being able to return this information as part of the same query as the depth. However, A user is likely to wish to specify their own time period (e.g. last 24 hours, last 1 hour etc). So perhaps a different query that can be merged with the depth data on the client. (ticket author not qualified to say, please re-write description as appropriate)

# Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios. Ideally, tasks would reflect the issues/pull requests likely to be created when developing the feature. 
- [ ] Short session to discuss brief with Front end team
- [ ] implement API
- [ ] Share with frontend team
- [ ] Respond to feedback from FE team

# Acceptance Criteria

- It is possible to see all the trades that have happened in the the last xxx amount of time (set buy user)
- it returns a sum for all the volume that has traded at each price level
- it is documented how the time period works (is it rolling 1h or from a time stamp to now)
- user can subscribe to changes

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature
