### ISSUE TITLE
GraphQL query complexity limit adjustment

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5720]
# Feature Overview

**In order to** prevent malicious queries from slowing down data nodes
**We will** reconfigure our graphql complexity limit
**So that** very complex queries are dropped instead of being executed

## Background
- https://gqlgen.com/reference/complexity/
- https://github.com/vegaprotocol/vega/issues/399#issue-593678824
- https://github.com/vegaprotocol/vega/blob/5a8785a3ce7cff73cb03866908a0d586a8c79599/datanode/gateway/graphql/server.go#L166-L168

# Tasks
- [ ] Ensure there are complexity number for all queries and fields
- [ ] Talk to @vegaprotocol/frontend to find a complex query, calculate its complexity
- [ ] Use that to set a default complexity limit (currently not set to anything)

# Acceptance Criteria
- Queries that are 'sufficiently complex' are dropped rather than executed

# Some evil queries
## Evil nesting, using pagination to avoid max GRPC query size 
```graphql
{
  markets {
    ordersConnection(pagination: { last: 10 }) {
      edges {
        node {
          party {
            id
          }
          market {
            id
            ordersConnection(pagination: { last: 10 })  {
              edges {
                node {
                  party {
                    id
                    ordersConnection(pagination: { last: 10 })  {
                      edges {
                        node {
                          market {
                            ordersConnection(pagination: { last: 10 })  {
                              edges {
                                node {
                                  market {
                                    accounts {
                                      balance
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
## Select _all_ the things (flat, with aliasing)
```graphql
{
  partiesConnection(pagination:{ last: 2 }) {
    edges {
      node {
        accounts {
 					balance
        }
      }
    }
  }
  marketsConnection(pagination:{ last: 2 }) {
    edges {
      node {
        ordersConnection(pagination:{ last: 2 }) {
 					edges {
            node {
              price
            }
          }
        }
      }
    }
  }
  orderVersionsConnection(pagination:{ last: 2 }) {
    edges {
      node {
        side
      }
    }
  }
  sameAgainButDifferent: orderVersionsConnection(pagination:{ first: 2 }) {
    edges {
      node {
        side
      }
    }
  }
  sameAgainButMoreDifferent: orderVersionsConnection(pagination:{ first: 10 }) {
    edges {
      node {
        side
      }
    }
  }
  proposalsConnection(pagination:{ last: 2 }) {
    edges {
      node {
        state
      }
    }
  }
  historicBalances(filter: { accountTypes: General }) {
    balance
  }
}
```

## Select _all_ the things (deeply nested remix)
```graphql
{
  partiesConnection(pagination:{ last: 2 }) {
    edges {
      node {
        accounts {
          market {
            tradesConnection(pagination: { first: 2}){
              edges {
                node {
                  buyer {
                    delegationsConnection( pagination: { last: 2 }) {
                      edges {
                        node {
                          epoch
                        }
                      }
                    }
                    proposalsConnection( pagination: { first: 2}) {
                      edges {
                        node {
                          datetime
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  transfersConnection(direction: ToOrFrom , pagination:{ first: 2 }) {
    edges {
      node {
        from
        to
        timestamp
        reference
        asset {
          id
          lpFeeRewardAccount {
            balance
            asset {
              globalRewardPoolAccount {
                balance
                asset {
                  takerFeeRewardAccount {
                    balance
                    asset {
                      makerFeeRewardAccount {
                        asset {
                          id
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
