### ISSUE TITLE
[graphql] transfersConnection query: direction should be an optional parameter

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5761]
https://github.com/vegaprotocol/vega/blob/06b241eb164a644994145f0e2db307533d8f5a77/datanode/gateway/graphql/schema.graphql#L581-L589

The old transfers API had an *optional* way to filter the requested transfers based on whether the specified party was the sender or receiver. The new API tidies this up to be a nicer enum specifying direction:

 https://github.com/vegaprotocol/vega/blob/06b241eb164a644994145f0e2db307533d8f5a77/datanode/gateway/graphql/schema.graphql#L3702-L3706

However! The query *requires* that direction is specified, while the older query defaulted to fetching both to and from. Given we already support `ToAndFrom`. we should replicate the old behaviour

# Task
- [ ] Remove `!` from graphQL schema
- [ ] Make query resolver default to `ToOrFrom`
- [ ] Ensure documentation around query is clear about this behaviour
