### ISSUE TITLE
[graphql] TransfersConnection should exist on Party

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5762]
# Feature Overview

**In order to** select transfers by a party
**We will** add a TransfersConnection property to the Party type in GraphQL
**So that** a graphql user can nest a transfers query

# Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios. Ideally, tasks would reflect the issues/pull requests likely to be created when developing the feature. 
- [ ] Add `TransfersConnection` property to Party, that resolves to transfers for the selected party

# Acceptance Criteria
A list of criteria (aim for 3!) that have to be met for this feature to be accepted as 'done' by the product owner.

- The following query works:

```graphql
{
  party(id: "network") {
    id
    transfersConnection(direction: ToOrFrom) {
      edges {
        node {
          id
          status
        }
      }
    }
  }
}
```

and the transfersConnection property is the same data as if I had queried:
```graphql
{
  transfersConnection(pubkey:"network", direction: ToOrFrom) {
    edges {
      node {
        id
        status
      }
    }
  }
}
```

Note: See #5761 for a note about the direction parameter

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature
