### ISSUE TITLE
Unclear error when "spam.protection.proposal.min.tokens" is higher than "governance.proposal.freeform.minProposerBalance"

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5786]
In Testnet right now, the network is configured as follows (full dump below, this is the relevant excerpt):
```json
{
    [
      {
        "key": "spam.protection.proposal.min.tokens",
        "value": "1000000000000000000"
      },
      {
        "key": "governance.proposal.freeform.minProposerBalance",
        "value": "0"
      }
   ]
}
```

I got the following error when submitting a proposal
> ✗ couldn't send transaction: InvalidArgument - party has insufficient tokens to submit proposal request in this epoch

Which was confusing. I had 5 tokens. 5 is greater than `governance.proposal.freeform.minProposerBalance`. so why do I have insufficient tokens?

The answer is: because the tokens *must be associated with the key* (and optionally also nominated), not in a general account balance. However.... _***which network parameter caused my transaction to be rejected***_? Was it because I had fewer staked than `spam.protection.proposal.min.tokens`, or is there a bug that meant that 0 is an invalid `...minProposerBalance`?

Note that submitting the same transaction with a freshly created key returns the same error, which suggests it´s the spam protection. But is it the spam protection for an account that has 0 balance in anything, or the spam protection for having fewer than `spam.protection.proposal.min.tokens`?

# Tasks
- [ ] Quick fix: Make testnet have a minProposerBalance for all proposal types that is equal to or greater than the spam min tokens value
- [ ] Quick fix: Improve the wallet error to clarify that tokens should be associated, not in the general account
- [ ] Investigate if with a spam min tokens set to 0, that it is allowable to perform a freeform proposal with 0 associated tokens
- [ ] Clarify in rejection reason which field is triggering the rejection

# Full network parameters
```json
{
  "networkParameters": [
    {
      "key": "governance.proposal.freeform.maxClose",
      "value": "8760h0m0s"
    },
    {
      "key": "governance.proposal.asset.minVoterBalance",
      "value": "1"
    },
    {
      "key": "market.value.windowLength",
      "value": "1h0m0s"
    },
    {
      "key": "market.liquidityProvision.shapes.maxSize",
      "value": "100"
    },
    {
      "key": "network.checkpoint.marketFreezeDate",
      "value": "never"
    },
    {
      "key": "spam.protection.max.delegations",
      "value": "390"
    },
    {
      "key": "reward.staking.delegation.competitionLevel",
      "value": "1.01"
    },
    {
      "key": "governance.proposal.updateMarket.minVoterBalance",
      "value": "1"
    },
    {
      "key": "market.margin.scalingFactors",
      "value": "{\"search_level\": 1.1, \"initial_margin\": 2.5, \"collateral_release\": 2.7}"
    },
    {
      "key": "governance.proposal.updateMarket.minProposerBalance",
      "value": "1"
    },
    {
      "key": "reward.staking.delegation.maxPayoutPerParticipant",
      "value": "700000000000000000000"
    },
    {
      "key": "limits.markets.proposeEnabledFrom",
      "value": ""
    },
    {
      "key": "governance.proposal.freeform.requiredMajority",
      "value": "0.66"
    },
    {
      "key": "governance.proposal.market.minProposerBalance",
      "value": "1"
    },
    {
      "key": "governance.proposal.freeform.requiredParticipation",
      "value": "0.00001"
    },
    {
      "key": "governance.proposal.updateMarket.minProposerEquityLikeShare",
      "value": "0.66"
    },
    {
      "key": "governance.proposal.updateNetParam.minProposerBalance",
      "value": "1"
    },
    {
      "key": "market.monitor.price.defaultParameters",
      "value": "{\"triggers\": [{\"auction_extension\": 300, \"horizon\": 43200, \"probability\": \"0.9999999\"}] }"
    },
    {
      "key": "governance.proposal.asset.minClose",
      "value": "1m0s"
    },
    {
      "key": "market.liquidity.stakeToCcySiskas",
      "value": "1.0"
    },
    {
      "key": "market.liquidity.maximumLiquidityFeeFactorLevel",
      "value": "1"
    },
    {
      "key": "governance.proposal.updateNetParam.maxEnact",
      "value": "8760h0m0s"
    },
    {
      "key": "market.stake.target.scalingFactor",
      "value": "0.1"
    },
    {
      "key": "market.auction.maximumDuration",
      "value": "168h0m0s"
    },
    {
      "key": "spam.protection.max.votes",
      "value": "20"
    },
    {
      "key": "transfer.fee.factor",
      "value": "0.001"
    },
    {
      "key": "validators.delegation.minAmount",
      "value": "100000000000000000"
    },
    {
      "key": "governance.proposal.asset.requiredMajority",
      "value": "0.66"
    },
    {
      "key": "market.liquidity.probabilityOfTrading.tau.scaling",
      "value": "10.0"
    },
    {
      "key": "governance.proposal.market.maxClose",
      "value": "8760h0m0s"
    },
    {
      "key": "governance.proposal.market.minEnact",
      "value": "2m0s"
    },
    {
      "key": "network.checkpoint.timeElapsedBetweenCheckpoints",
      "value": "1m"
    },
    {
      "key": "market.auction.minimumDuration",
      "value": "10s"
    },
    {
      "key": "governance.proposal.updateNetParam.minVoterBalance",
      "value": "1"
    },
    {
      "key": "market.monitor.price.updateFrequency",
      "value": "1s"
    },
    {
      "key": "network.validators.ersatz.multipleOfTendermintValidators",
      "value": "0.5"
    },
    {
      "key": "network.validators.multisig.numberOfSigners",
      "value": "13"
    },
    {
      "key": "governance.proposal.updateNetParam.requiredParticipation",
      "value": "0.3"
    },
    {
      "key": "market.liquidity.providers.fee.distributionTimeStep",
      "value": "0m"
    },
    {
      "key": "governance.proposal.updateMarket.requiredParticipation",
      "value": "0.3"
    },
    {
      "key": "reward.staking.delegation.minValidators",
      "value": "5"
    },
    {
      "key": "spam.pow.increaseDifficulty",
      "value": "0"
    },
    {
      "key": "snapshot.interval.length",
      "value": "1000"
    },
    {
      "key": "market.liquidityProvision.minLpStakeQuantumMultiple",
      "value": "1"
    },
    {
      "key": "governance.proposal.asset.requiredParticipation",
      "value": "0.5"
    },
    {
      "key": "network.floatingPointUpdates.delay",
      "value": "5m"
    },
    {
      "key": "network.validators.minimumEthereumEventsForNewValidator",
      "value": "3"
    },
    {
      "key": "validators.vote.required",
      "value": "0.67"
    },
    {
      "key": "market.fee.factors.makerFee",
      "value": "0.0002"
    },
    {
      "key": "reward.staking.delegation.delegatorShare",
      "value": "0.883"
    },
    {
      "key": "governance.proposal.market.minClose",
      "value": "1m0s"
    },
    {
      "key": "governance.proposal.updateNetParam.requiredMajority",
      "value": "0.5"
    },
    {
      "key": "governance.proposal.updateNetParam.minEnact",
      "value": "24h0m0s"
    },
    {
      "key": "governance.proposal.updateMarket.minEnact",
      "value": "1h0m0s"
    },
    {
      "key": "reward.staking.delegation.payoutFraction",
      "value": "0.007"
    },
    {
      "key": "governance.proposal.updateNetParam.minClose",
      "value": "24h0m0s"
    },
    {
      "key": "spam.protection.voting.min.tokens",
      "value": "1000000000000000000"
    },
    {
      "key": "limits.assets.proposeEnabledFrom",
      "value": ""
    },
    {
      "key": "governance.proposal.updateNetParam.maxClose",
      "value": "8760h0m0s"
    },
    {
      "key": "spam.protection.max.proposals",
      "value": "20"
    },
    {
      "key": "spam.protection.maxUserTransfersPerEpoch",
      "value": "20"
    },
    {
      "key": "market.liquidity.minimum.probabilityOfTrading.lpOrders",
      "value": "1e-8"
    },
    {
      "key": "blockchains.ethereumConfig",
      "value": "{\"network_id\": \"3\", \"chain_id\": \"3\", \"collateral_bridge_contract\": { \"address\": \"0x3d76e9779d730b096301B1133395c8B6a352c3aA\" }, \"multisig_control_contract\": { \"address\": \"0xD3354ea2f9060acdC291470a09c1eBc402455c8a\", \"deployment_block_height\": 12350281 }, \"staking_bridge_contract\": { \"address\": \"0xF5A3830F002BE78dd801214F5316b677E0355c60\", \"deployment_block_height\": 11340807 }, \"token_vesting_contract\": { \"address\": \"0xe2deBB240b43EDfEBc9c38B67c0894B9A92Bf07c\", \"deployment_block_height\": 11340808 }, \"confirmations\": 3}"
    },
    {
      "key": "governance.proposal.freeform.minVoterBalance",
      "value": "0"
    },
    {
      "key": "governance.proposal.market.maxEnact",
      "value": "8760h0m0s"
    },
    {
      "key": "governance.proposal.market.requiredMajority",
      "value": "0.66"
    },
    {
      "key": "reward.asset",
      "value": "fc7fd956078fb1fc9db5c19b88f0874c4299b2a7639ad05a47a28c0aef291b55"
    },
    {
      "key": "governance.proposal.asset.maxClose",
      "value": "8760h0m0s"
    },
    {
      "key": "governance.proposal.market.requiredParticipation",
      "value": "0.5"
    },
    {
      "key": "governance.proposal.updateMarket.requiredMajorityLP",
      "value": "0.66"
    },
    {
      "key": "governance.proposal.freeform.minClose",
      "value": "48h0m0s"
    },
    {
      "key": "reward.staking.delegation.minimumValidatorStake",
      "value": "3000000000000000000000"
    },
    {
      "key": "spam.protection.delegation.min.tokens",
      "value": "1000000000000000000"
    },
    {
      "key": "governance.proposal.updateMarket.maxEnact",
      "value": "8760h0m0s"
    },
    {
      "key": "validators.epoch.length",
      "value": "2h"
    },
    {
      "key": "network.validators.tendermint.number",
      "value": "30"
    },
    {
      "key": "reward.staking.delegation.maxPayoutPerEpoch",
      "value": "7000000000000000000000"
    },
    {
      "key": "market.stake.target.timeWindow",
      "value": "1h0m0s"
    },
    {
      "key": "market.fee.factors.infrastructureFee",
      "value": "0.0005"
    },
    {
      "key": "network.validators.ersatz.rewardFactor",
      "value": "0.5"
    },
    {
      "key": "governance.proposal.updateMarket.requiredParticipationLP",
      "value": "0.00001"
    },
    {
      "key": "spam.pow.numberOfPastBlocks",
      "value": "100"
    },
    {
      "key": "spam.pow.numberOfTxPerBlock",
      "value": "100"
    },
    {
      "key": "market.liquidity.bondPenaltyParameter",
      "value": "0.00001"
    },
    {
      "key": "market.liquidity.targetstake.triggering.ratio",
      "value": "0.7"
    },
    {
      "key": "governance.proposal.asset.minEnact",
      "value": "2m0s"
    },
    {
      "key": "reward.staking.delegation.payoutDelay",
      "value": "6h"
    },
    {
      "key": "spam.protection.proposal.min.tokens",
      "value": "1000000000000000000"
    },
    {
      "key": "governance.proposal.updateMarket.maxClose",
      "value": "8760h0m0s"
    },
    {
      "key": "governance.proposal.asset.maxEnact",
      "value": "8760h0m0s"
    },
    {
      "key": "network.checkpoint.networkEndOfLifeDate",
      "value": "never"
    },
    {
      "key": "transfer.minTransferQuantumMultiple",
      "value": "0.1"
    },
    {
      "key": "spam.pow.difficulty",
      "value": "15"
    },
    {
      "key": "governance.proposal.asset.minProposerBalance",
      "value": "1"
    },
    {
      "key": "governance.proposal.updateMarket.minClose",
      "value": "1h0m0s"
    },
    {
      "key": "spam.pow.hashFunction",
      "value": "sha3_24_rounds"
    },
    {
      "key": "governance.proposal.updateMarket.requiredMajority",
      "value": "0.66"
    },
    {
      "key": "network.validators.incumbentBonus",
      "value": "1"
    },
    {
      "key": "governance.proposal.freeform.minProposerBalance",
      "value": "0"
    },
    {
      "key": "governance.proposal.market.minVoterBalance",
      "value": "1"
    },
    {
      "key": "reward.staking.delegation.optimalStakeMultiplier",
      "value": "3.0"
    }
  ]
}
```

**Comment by gordsport** [comment]
Closing as fixed, error message has been updated to be more clear
