### ISSUE TITLE
Can't vote on a new asset proposal in `WaitingForNodeVote`

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5816]
# Problem encountered
I submitted a `NewAsset` proposal and it sat in the state `WaitingForNodeVote` for a while (which may or may not be correct, but hey). According to https://github.com/vegaprotocol/vega/blob/fc24100ccc418bb03f3ae99342eaa65c951acbc8/core/governance/engine.go#L1014-L1017 I should be able to vote on it. So I voted, but the vote never counted.

# Observed behaviour
I made a proposal
I voted on it
The vote is not shown under my party in graphql
The vote count on the proposal is 0 in graphql and rest

# Expected behaviour
The vote should count

# Steps to reproduce
Make a new asset proposal, something like:
```bash
./vegawallet command send --wallet test --pubkey 6eed3515524b3c6dda7a9eceaebba58e236a56faa8ef7b8129179c9d269f41f2 --network fairground '{
 "proposalSubmission": {
  "rationale": {
   "description": "Add Moana (MOL)"
  },
  "terms": {
   "newAsset": {
    "changes": {
     "name": "Solana",
     "symbol": "SOL",
     "totalSupply": "19010568",
     "decimals": "5",
     "quantum": "1",
     "erc20": {
      "contractAddress": "0xcb84d72e61e383767c4dfeb2d8ff7f4fb89abc6e",
      "withdrawThreshold": "10",
      "lifetimeLimit": "10"
     }
    }
   },
   "closingTimestamp": 1659980762,
   "enactmentTimestamp": 1659984422,
   "validationTimestamp": 1659977162 
  }
 }
}'
```

Ensure the NewAsset details are correct - that the ERC0 token contract exists at that address on ropsten and returns the same details

Now, vote on the proposal. Note, as there was no spec for this, token frontend does not allow voting on a proposal in this state. So you'll have to do some messing around if you want a UI. Anyway. You'll get something like:

https://explorer.fairground.wtf/txs/0xDD5E8F9E91DC1714647587FDA4267C890FDF9715ADC0C1A3507CEFA464CEB1DA

A vote for that proposal. However the vote count will be 0

# Tasks
- [ ] Find out why a vote on a New Asset proposal in the state `WaitingForNodeVote` is not counted
- [ ] Ensure that is should be counted
- [ ] Assuming it should be counted, make it be counted
- [ ] If it shouldn't, fix https://github.com/vegaprotocol/vega/blob/fc24100ccc418bb03f3ae99342eaa65c951acbc8/core/governance/engine.go#L1014-L1017
