### ISSUE TITLE
Include a reason that an order was `Stopped` in API

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vega#5915]
# Feature Overview

**In order to** tell the user why an order was stopped
**We will** add a new field to the API
**So that** we can show which of the various reasons made the order have the status of `Stopped`

for example an order could be stopped due to lack of collateral (margin call) or because a FOK didn't hit enough volume to be filled

## Specs
- reasons for stopped or rejected are not mentioned in the spec (at Time of writing).
- but there is a precedent: `rejected` orders get a rejected reason. https://docs.vega.xyz/docs/mainnet/graphql/enums/order-rejection-reason (note that the reasons are enum not string, this is very useful for documentation

# Tasks
- [ ] consider re-purposing the existing rejectedReason field or not (e.g. rename to ~rejected~Reason) 
- [ ] include all the reasons an order can be stopped in the enums
- [ ] update the API and let clients know

deprecating `Rejected reason` and creating a new `reason` field that can contain both `Stopped` and `rejected` reasons, I think, will give the better DevEx. 

# Acceptance Criteria
A list of criteria (aim for 3!) that have to be met for this feature to be accepted as 'done' by the product owner.

- for order that have a status of `Stopped` I can see a reason that the order was stopped

# Test Scenarios
Detailed scenarios (1-3!) that can be executed as feature tests to verify that the feature has been implemented as expected. We use the follow format:

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/integration/) for more format information and examples.

# Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature. 

# Examples (optional)
Code snippets from the spec for reference

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
Hi @campbellssource 
https://github.com/vegaprotocol/specs/pull/1319/files

This PR lists out the error messages used by core. the other linked issue in this PR is to make that more clear (above AC entries) in the spec.
