### ISSUE TITLE
Swagger generated from protos seems incorrect

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6036]
https://github.com/vegaprotocol/vega/pull/5976 added a task that automatically generates a pull request for the documentation site containing (amongst other docs) a Swagger document, generated by buf from the protos.

However, the version it commits contains no paths, which means for https://github.com/vegaprotocol/docs the Swagger browser is useless. The reason it's useless is the 'bad' version contains an empty `paths` property. Why is a mystery.

# Bad
This one was generated automatically by the pull request
https://github.com/vegaprotocol/documentation/blob/main/specs/v0.54.0/swagger/data-node/api/v2/trading_data.swagger.json

# Good
This one was generated by @jeremyletang 
https://github.com/vegaprotocol/documentation/blob/main/data/v0.54/trading_data_v2.swagger.json

# Test of goodness
If you upload the generated doc to https://redocly.github.io/redoc/ and it has more than just 'TradingDataService' in the left hand column, it's good

# Tasks
- [x] Work out why the PR creates a path-less swagger file
- [x] Make it generate paths
- [ ] Update server URL

**Comment by edd** [comment]
When I regenerate them manually for 0.55 this happens to me too. Well, at least it's consistent!
