### ISSUE TITLE
[data node] New endpoints lack documentation

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6133]
https://github.com/vegaprotocol/vega/blob/develop/datanode/gateway/graphql/schema.graphql

This should have docblocks for all queries. Frequently the new ones don't, where the old ones do:
https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L369-L377

# Tasks: Queries MUST have docs
- [x] Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L359
- [x] Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L372
- [x] Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L408
- [x] Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L602
- [x] Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L657
- [x] Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L874
- [x] Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L886
- [ ] Add docs for https://github.com/vegaprotocol/vega/blob/develop/datanode/gateway/graphql/schema.graphql#L989
- [ ] Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L874
- [ ] Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L886

## Optional extra (can be another ticket): Types should all have documentation
-  Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L710
-  Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L781
-  Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L791
-  Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L802
-  Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L826
-  Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L837

-  Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L842
-  Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L861
- Add docs for https://github.com/vegaprotocol/vega/blob/a046379e01699f378ac86538592e6cbf06d3c29a/datanode/gateway/graphql/schema.graphql#L896
