### ISSUE TITLE
Standardise GraphQL 'no result' results

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6332]
(wip ticket)

# Feature Overview

**In order to** provide consistent information to API users
**We will** make sure all queries report 'no result's consistently
**So that** it's less surprising

# Background
**Note: party here is an illustration, a stand in for all queries**

We have inconsistent nullability and errors with return types on our queries. The way we return a result for a specific party, if the party doesn't exist, breaks the schema by returning null and an error field, where the schema says it will never be null. 

# Tasks
- [ ] Ensure the result of a query matches the schema
  - [ ] `party` should *not* return an `error` field if the specified ID does not exist. It should return party as null
  - [ ] `partyConnection` should always return an array, even if it is empty (i.e. `partyConnection: [Party!]!` - there will always be an array and any item in the array will be a Party)
- [ ] Do the same for markets
- [ ] And assets
- [ ] And proposals
- [ ] And so on
