### ISSUE TITLE
Block explorer protos provides inadequate REST information

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6484]
Corestate sets the following properties:

https://github.com/vegaprotocol/vega/blob/74e5fdc9a8bfe68b314212bf83c6359d6d853386/protos/sources/vega/api/v1/corestate.proto#L14-L21

While they're imperfect (lb.testnet.vega.xyz is no longer a valid server), they do at least:
- Set a version that represents that Vega version
- Sets a server that can be used to access the API

I've set a bonus task, which is to actually use a valid server. However the docs scripts already replace the invalid server with a valid one, and the docs repo is currently the only known downstream client of the protos, so an invalid server is fine *for now*. If the bonus task is too much work, create an alternate ticket. None of these are blocking, as I fix them downstream either manually or automatically anyway.

# Tasks
- [ ] Add openapiv2_swagger Name and Version properties to Block Explorer proto
- [ ] Add servers property with invalid server to block explorer proto

# Bonus task
- [ ] Work out how to populate the server field with a single valid server
