### ISSUE TITLE
Check / Update Network Parameter Validation Ranges

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#6582]
# Feature Overview

**In order to** ensure that the network parameters are within the specified ranges
**We will** add the ranges into the code for each network parameter (somewhere "next to" keys.go ?)
**So that** we can test that the parameters are within range and link to these files from the spec so the spec does not go out-of-date

## Specs
- [Ranges to be added](https://docs.google.com/spreadsheets/d/1tz9t2wYJ5kEFkngfYowPWKHhN4aTgRFM2O2rSOAoyvw/edit#gid=453838910)

# Tasks
- [ ] add the ranges (if not added) or check they match those defined in the spreadsheet

Once done @gordsport to open a specs issue to:
- [ ] link the files in the specs
- [ ] create acceptance criteria (and codes) for the net param ranges

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by davidsiska-vega** [comment]
@vegaprotocol/core Whoever ends up implementing this: if you think any of the values are inappropriate shout - we can discuss.

**Comment by ze97286** [comment]
@davidsiska-vega I left a few comments on the spreadsheet

**Comment by davidsiska-vega** [comment]
@ze97286 We can make the minimum auction duration whatever is needed for system tests to run "fast". Would you care to edit the range?

**Comment by davidsiska-vega** [comment]
@ze97286 As for not supporting the "additional constraints" - we probably should but not necessarily as part of this ticket I suppose. 

Though I worry about leaving the system in a an "undefined" state.

**Comment by davidsiska-vega** [comment]
@ze97286 for `reward.staking.delegation.minValidators` isn't this just a number that goes into a formula rather than a limit on the minimum validators the network will run with? But if it is then change the spreadsheet value to `1`.

**Comment by davidsiska-vega** [comment]
@ze97286 I've edited the range for `reward.staking.delegation.optimalStakeMultiplier`.

**Comment by ze97286** [comment]
> @ze97286 for `reward.staking.delegation.minValidators` isn't this just a number that goes into a formula rather than a limit on the minimum validators the network will run with? But if it is then change the spreadsheet value to `1`.

it is a number that goes into the calculation of the optimal stake. when it's disconnected from the actual number of the nodes in the network it makes it harder to control in system tests.

**Comment by davidsiska-vega** [comment]
> it is a number that goes into the calculation of the optimal stake. when it's disconnected from the actual number of the nodes in the network it makes it harder to control in system tests. 

I've changed to `1`.

**Comment by davidsiska-vega** [comment]
I've changed `network.validators.tendermint.number` and `network.validators.multisig.numberOfSigners` to `1<=x<=...` because of the system tests comment you've left @ze97286 .

**Comment by ze97286** [comment]
what is the last tab doing there? it's not network parameters right?

**Comment by davidsiska-vega** [comment]
> what is the last tab doing there? it's not network parameters right? 

Those are the lognoral risk model parameter ranges. Perhaps should be validated at market proposal / change but it's not part of this ticket I suppose.
