### ISSUE TITLE
[block explorer api] Fetch transactions by block

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6789]
# Description
## What we have now (ref: https://docs.vega.xyz/testnet/category/api/rest/explorer/block-explorer):

- List all transactions (before/after by cursor)
- Get specific transaction by ID

## The gap
This lets us list all transactions, in a list. Which is great! What it doesn't do is let us show all of the transactions in a specified block. For this the current explorer relies [on an API that is only sort of semi supported](https://github.com/vegaprotocol/explorer/blob/master/api/main.go) - we can post in a block height and a node, and get out all the TXs decoded. 

## Tasks
- [ ] Either add a new endpoint (getTxsByBlock) or a new filter for the existing listTransactions endpoint
  - [ ] Must take a `blockHeight` parameter
  - [ ] Must return all transactions decoded from that block

## References
- https://etherscan.io/txs?block=15947319

**Comment by pscott31** [comment]
You can actually do this now in two different ways

you can filter on it as well using the key "tx.height", but it might not be super quick depending on how many rows there are because it's looking at the generic 'attribute events' that TM stores.

A cheesy but fast way:  the cursor is actually <block_height>.<sequence_number> so if you say ?after=10.0&before=11.0 you should get all the stuff in block 10.

**Comment by pscott31** [comment]
but I'll add an obvious way to do it :)
