### ISSUE TITLE
[explorer] API returns 

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6870]
```sh
curl 'https://explorer.vega.trading/.netlify/functions/chain-explorer-api' -X POST -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:107.0) Gecko/20100101 Firefox/107.0' -H 'Accept: */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: http://localhost:3000/' -H 'Content-Type: application/json' -H 'Origin: http://localhost:3000' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'TE: trailers' --data-raw '{"block_height":108,"node_url":"https://tm.be.testnet.vega.xyz/"}'
```

Returns:

```json
{"errorMessage":"proto: cannot parse invalid wire-format data","errorType":"prefixError"}
```

The block has one transaction:
```sh
curl 'https://tm.be.testnet.vega.xyz/block?height=108' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:107.0) Gecko/20100101 Firefox/107.0' -H 'Accept: */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: http://localhost:3000/' -H 'Origin: http://localhost:3000' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'TE: trailers'
```

```json
      "data": {
        "txs": [
          "Cr8FCLXJz5vO3a/RpgEQa+o+rgUKKHJWY1NESllmazNOaTZ5aTlad1ZjWVhGYVNBNm1pVVp1Y0hkemRHQ3YS2QQIqfC5mwYQq/G5mwayBskECsYECvkCChlCVENVU0QgTW9udGhseSAoRGVjIDIwMjIpEgtCVENVU0QuTUYyMaIGzQIKQGIzNDBjMTMwMDk2ODE5NDI4YTYyZTVkZjQwN2ZkNmFiZTY2ZTQ0NGI4OWFkNjRmNjcwYmViOTg2MjFjOWM2NjMSA1VTRBppEmcKZQpECkIKQDY5NDY0ZTM1YmNiOGU4YTI5MDBjYTBmODdhY2FmMjUyZDUwY2YyYWIyZmM3MzY5NDg0NWExNmI3YzhhMGRjNmYSHQoUChBwcmljZXMuQlRDLnZhbHVlEAISBQgBEgExIm4SbApqCkQKQgpANjk0NjRlMzViY2I4ZThhMjkwMGNhMGY4N2FjYWYyNTJkNTBjZjJhYjJmYzczNjk0ODQ1YTE2YjdjOGEwZGM2ZhIiChkKFXRlcm1pbmF0aW9uLkJUQy52YWx1ZRAEEgUIARIBMSopChBwcmljZXMuQlRDLnZhbHVlEhV0ZXJtaW5hdGlvbi5CVEMudmFsdWUQBRoZZm9ybWVybHk6MDc2QkI4NkE1QUE0MUUzRRoIYmFzZTpCVEMaCXF1b3RlOlVTRBoPY2xhc3M6ZngvY3J5cHRvGgdtb250aGx5Gg1zZWN0b3I6Y3J5cHRvGgthdXRvOmJ0Y3VzZCIjChIIwNECEgkwLjk5OTk5OTkY2AQKDQisAhIGMC45OTk5GDwqEAoMCJAcEQAAAAAAACRAGAEwA6oGJgktQxzr4jYaPxGFOwuKvO/zPhoSEfyp8dJNYpA/GQAAAAAAAPQ/GiYKEU5ldyBCVENVU0QgTWFya2V0IhFOZXcgQlRDVVNEIG1hcmtldBKTAQqAATI2NzZhMDNlMWUxOGQ1YWNmZWIyZWY2NWRhZDgwMjg5ODkzNmE0MjVhYmIzN2ZhYTg2MmU5YTMxMjNlNWI3NzViMWJhZmI1ZDQ0ZDMxYTE2ZDllMGE4MTUzMGUyNzkyMjQxYWUyNGY5NDEyMTVmZmNkNzFjNDIwNzAxYzIwNTBjEgx2ZWdhL2VkMjU1MTkYAYB9A8K7AUUKQDdDNkRFQzlCMUI2REVFMEJGMTUxOEFBN0NERENEMTA1MkYyMDdCOEY5RTVGMDk3N0NBRUUwREVFRkE3RTU3RDgQ3inSPkA2OTQ2NGUzNWJjYjhlOGEyOTAwY2EwZjg3YWNhZjI1MmQ1MGNmMmFiMmZjNzM2OTQ4NDVhMTZiN2M4YTBkYzZm"
        ]
      },
```

# Tasks
- [ ] Work out what TX this is that won't decode
- [ ] Make explorer API decode it
- [ ] Update explorer API

**Comment by edd** [comment]
https://github.com/vegaprotocol/vega/issues/6880 is the fix
