### ISSUE TITLE
[datanode] statistics should not be a proxy to core statistics

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#6913]
# Feature Overview

**In order to** correctly diagnose if a data node is healthy or unhealthy
**We will** change the statistics  endpoints in rest/graphql/grpc to represent the statistics from the data node's point of view
**So that** we can compare what the *data node* thinks the block height is to what the *vega node* thinks it is

# Current situation
https://docs.vega.xyz/testnet/api/rest/core/core-service-statistics is a **core** service. It gives us (key to this ticket) a block height.
https://docs.vega.xyz/testnet/api/graphql/queries/statistics is a GraphQL query - i.e. served by data node - but it actually just gives us the same result as the **core** service. This is a problem in, for example, https://github.com/vegaprotocol/vaguer

## Why it's a problem in Vaguer
Vaguer runs [a big ol' GraphQL query](https://github.com/vegaprotocol/vaguer/blob/main/src/lib/check.js#L7-L78) for some data. It then hashes parts of that query to compare the current version of the state. A key to this being useful is to only compare nodes that are at the same height. But if statistics comes from the vega node, and the data node is lagging behing in ingesting events, the GraphQL query will look like it is reporting the data-node's data for block height X, but it's actually at an unknowable height in terms of ingesting events

## But we added `x-block-height` header
It also uses the core idea of what the block height is, not the data-node

## So how do you know the data-node is at a different height?
There is no reliable way. What it IS possible to do is call an [epoch endpoint](https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-get-epoch) on data node, and  [the core statistics service](https://docs.vega.xyz/testnet/api/rest/core/core-service-statistics) and compare the current epoch between them. If the data-node is lagging behind, the epoch's *might* be different. Although depending on how long an epoch is, that may not be the case.

## Why does it matter
It matters because data-node can appear to be serving incorrect data for a block height. If core is at block 100, and at block 90 a new asset was created, and data node says it is at block 100 but has actually only processed events up to block 50, then the asset appears not to exist at block height 100. The only reliable way to know this is an error now is to switch data node, or compare epochs as above, neither of which is intiuitive.

# Tasks
- [ ] GraphQL statistics endpoint should not use the core statistics endpoint as its source of truth
- [ ] Trading data REST APIs v1 & v2 statistics endpoint should not use the core statistics endpoint as their source of truth
- [ ] Reduce the statistics endpoint [to these fields](https://github.com/vegaprotocol/vega/issues/2155#issuecomment-681943044)
- [ ] Source the data for those fields from data-nodes data stores
