### ISSUE TITLE
Remove the deprected `encodedTransaction` fields

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#7010]
**Affected endpoints:**
- `admin.send_transaction`
- `admin.sign_transaction`
- `client.send_transaction`
- `client.sign_transaction`

**Tasks**
- [ ] Update the openrpc.json
- [ ] Update the documentation
- [ ] Remove properties in code
- [ ] Remove related test
