### ISSUE TITLE
btcsuite/btcd mishandles witness size checking

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7073]
### Issue

GitHub has flagged the following security risk:

[btcd mishandles witness size checking](https://github.com/vegaprotocol/vega/security/dependabot/12)

This is marked as a 9.8/10 CVSS score.

Seems we are on [v0.22.1](https://github.com/vegaprotocol/vega/blob/develop/go.mod#L303) and the secure version is v0.23.2 

- they also patched this to v0.23.3 in November. Release notes [here](https://github.com/btcsuite/btcd/releases).

### Tasks

- [ ] investigate the changes between 0.22.1 and the latest
- [ ] assess any impact / work that may be caused by updating 
- [ ] update versions and test fully

**Comment by ze97286** [comment]
https://github.com/btcsuite/btcd/compare/v0.22.1...v0.22.2
