### ISSUE TITLE
[swagger] Required fields not marked as required

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#7108]
This REST api request will fail:
```shell
curl -L -X GET 'https://api.n06.testnet.vega.xyz/api/v2/candle' -H 'Accept: application/json'
```

It'll fail with this error:
```json
{
  "code": 13,
  "message": "Internal error",
  "details": [
    {
      "@type": "type.googleapis.com/vega.ErrorDetail",
      "code": 60001,
      "message": "failed to get candle data",
      "inner": "getting candle data for time span:invalid candle id:"
    }
  ]
}
```

So the ID is required. However in the swagger file (generated by https://github.com/vegaprotocol/vega/blob/develop/.github/workflows/release-docs.yml) we get:

```javascript
// .... snip 
{
   "/api/v2/candle": {
      "get": {
        "summary": "Candles list",
        "description": "Get candle data for a given candle id",
        "operationId": "TradingDataService_ListCandleData",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/v2ListCandleDataResponse"
            }
          },
          "default": {
            "description": "An unexpected error response.",
            "schema": {
              "$ref": "#/definitions/googlerpcStatus"
            }
          }
        },
        "parameters": [
          {
            "name": "candleId",
            "description": "Candle identifier, required field.",
            "in": "query",
            "required": false,   // <---------
            "type": "string"
          },
          {
            "name": "fromTimestamp",
            "description": "Timestamp to retrieve candles since, in nanoseconds since the epoch,\nrequired field - See [`VegaTimeResponse`](#api.VegaTimeResponse).`timestamp`.",
            "in": "query",
            "required": false,
            "type": "string",
            "format": "int64"
          },
// .....

```

Which is untrue, and causes the docs page (e.g. https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-list-candle-data to render the parameter as optional

# Tasks
- [ ] For all REST services (`core`, `corestate`, `trading_data_v2`, `block_explorer`)
  - [ ] For all REST api requests
    - [ ] Find the required parameters
    - [ ] Ensure the protos are marked with a comment that generates them as `required` in swagger
    - [ ] Ensure that the fields that are not required (like candle id above) are not marked as required

## Notes
- The fields are generally marked  correctly in graphql

**Comment by jeremyletang** [comment]
I've looked into that for a minutes, seems like we need to add the following kind of annotation to every fields:
```
string candle_id = 1 [(google.api.field_behavior) = REQUIRED];
```
And import the following extra protos.

```
import "google/api/annotations.proto";
import "google/api/field_behavior.proto";
```

I'm not sure how much we'll want to do that. I'll move that in oregon trail stretch for now.

**Comment by candida-d** [comment]
This is not complete.

**Comment by gordsport** [comment]
@candida-d 

In discussions on this issue we believe that the ideal solution is to update the docs generator. Its thought that the doc generator doesn't know that if don't say `optional` its implied that it is actually `required`. Its possible that this is the case as `optional` is quite a new protobuf feature.

If you are in agreement I can close this issue and link it to a new issue on the docs repo to investigate

**Comment by edd** [comment]
@gordsport No, it's not a documentation team task to fix. Otherwise I think we agree 😄 

Just so we’re all aligned on what we’re talking about: 
1. The swagger (openapiv2) files are generated by this makefile action in `vegaprotocol/vega`: https://github.com/vegaprotocol/vega/blob/develop/Makefile#L93. It uses protoc and this plugin: https://github.com/vegaprotocol/vega/blob/develop/script/gettools.sh#L7-L8
2. When vegaprotocol/vega is tagged with a new release this Github action in `vegaprotocol/vega` generates the swagger documents and opens then as a PR for `vegaprotocol/documentation`: https://github.com/vegaprotocol/vega/blob/develop/.github/workflows/release-docs.yml#L40-L53)
3. The HTML documentation is generated by https://github.com/PaloAltoNetworks/docusaurus-openapi-docs (note: technically after being converted from swagger/openapiv2 to openapiv3

We're all talking about fixing step 1. `v2.7.3` is outdated - there's a `v2.15.x`, but for our code it generates the same output - merely updating it won't work. Again, as you said above - we probably need an alternative plugin. Finding a plugin, or as @jeremyletang mentioned above, proto annotations, that mark fields as required, is a job for people who work with the protos. I expect the swagger file that is PRd in to documentation in step 2 to correctly contain `required` fields.

**Comment by wwestgarth** [comment]
I don't believe that switching to a tool that understand "optional" will be enough. We have API with fields that are **not** marked as optional, but an empty string means to not filter by that field. So in these cases they will be marked as required when they are not. 

Example:
```
// Request for listing margin levels
message ListMarginLevelsRequest {
    // Party ID for which to list the margin levels
    string party_id = 1;
    // Market ID for which to list the margin levels
    string market_id = 2;
    // Pagination control
    Pagination pagination = 3;
}
```
query works without a partyId/marketId:
https://api.devnet1.vega.xyz/api/v2/margin/levels

So we'd have to do something about those either by finding all occurences and making a breaking changes to put `optional` in front of them, or by not caring about the `optional` tag an putting `[(google.api.field_behavior) = REQUIRED]` everywhere. Eitherway just updating the tooling won't be enough here.
