### ISSUE TITLE
Asset Icons

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vega#7203]
# Feature Overview

**In order to** Allow frontends to display logos
**We will** Add the ability to query logo/icon by asset id
**So that** Frontends can know where to get the icon for a given asset

## Specs

N/A

# Tasks

Dependent on implementation

# Acceptance Criteria

- It is possible to take a vega asset id and get a URL pointing to the icon for that asset

# Additional Details (optional)

Possibly a github repo with the mapping would be adequate for this. Not sure if this make sense from a core perspective. 

# Examples (optional)
Code snippets from the spec for reference

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
Hey @dexturr 
This has been triaged and deemed as something we would not support in the core. Logos and the surrounding functionality should be managed in the FE applications.
Lets catch up to discuss further if you really diasagree.

**Comment by barnabee** [comment]
There are a couple of decent looking sources of this kind of data listed [here](https://ethereum.stackexchange.com/questions/33679/is-there-an-api-that-can-find-all-the-erc20-token-icons#33730)
