### ISSUE TITLE
Reduce passphrase requests for admin endpoints

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#7223]
## Story 
As a user 
I want to enter my wallet passphrase(s) only once in a session
So that I can concentrate on what I'm trying to get done (rather than need to enter my password all the time)

## Acceptance Criteria 
- [ ]  I am only asked for a password once per session (until I reboot)
- [ ] For subsequent actions via the admin endpoint (create a wallet, view locked wallet, update permissions, change key name, import a wallet...) I am only asked a password once
- [ ] When I enter a password triggered by a client endpoint e.g. a new wallet connection, and then go to do something using the admin endpoint like viewing that wallet, I don't have to enter the password again (even if that wallet was locked before) and vice versa 

## Tasks 
- [ ] Implement a shared session history for admin and client endpoints to minimise password requests
- [ ] ...

## Background
Right now all changes to the wallet API require a passphrase to be entered to be executed - via admin endpoint and client endpoint. This passphrase in used to decrypt and encrypt the wallet file. Each wallet has its own password, and session history is only saved right now for just the client endpoint actions (update permissions, new connection...)
 
For example:
1. GetWallet(passphrase)
1. GenerateKey(passphrase)
1. ListKeys(passphrase)
1. TaintKey(passphrase)

This ticket should replace asking a passphrase for every action with a locking mechanism / session history, that would unlock the wallet once, keep the passphrase in memory and reuse when needed. Reusing the example below, that would give:

User unlocks wallet 
1. UnlockWallet(passphrase)

Then... doesn't have to enter password again
1. GetWallet()
1. GenerateKey()
1. ListKeys()
1. TaintKey()
1. LockWallet()
