### ISSUE TITLE
Block Explorer API - batch transaction errors

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#7245]
# Feature Overview

**In order to** usefully render the success or failure of a batch order
**We will** need improve on the simply returning the `error field`
**So that** individual transactions in the batch can be marked as successful or failed
and the success of the batch as a whole can be represented

# Tasks
- [ ] Determine where exactly the errors should sit
- [ ] Put the errors along with the invidual commands rather than all in one API field
- [ ] Decide how best to represent the success of the batch as a whole (is it if any passes it's all fine? Is a batch status even meaningful?)

# Acceptance Criteria
A list of criteria (aim for 3!) that have to be met for this feature to be accepted as 'done' by the product owner.
- [ ] Every `cancellation` has an associated error message if it failed
- [ ] Every `submission` has an associated error message if it failed
- [ ] Every `amendment` has an associated error message if it failed

# Test Scenarios
GIVEN a batch transaction with 2 cancellations
WHEN the first cancellation is for an order that does not exist
THEN the cancellation within the `command` object has an error field and that error field contains the error `unable to find the order in the market`

GIVEN a batch transaction with 2 amendments
WHEN the first amendment is for an order that is filled
THEN the amendment within the `command` object has an error field and that error field contains the error

GIVEN a batch transaction with 2 submissions
WHEN the first order is for a market that does not exist
THEN the order within the `command` object has an error field and that error field contains the error

# Additional Details (optional)
This is part of a set of Block Explorer API requests that change the intent of the Block Explorer API from 'return precisely what is in the command' to 'return the details a client needs to render the appropriate details for a transaction'. Ideally we can go through a proper API planning excercise for this, but this ticket can be addressed as is.

# Examples (optional)
```
curl 'https://be.testnet.vega.xyz/rest/transactions/4D534CA14B04D37B62A6D3055332EC8DADB73B4DC10AF7631DDA601A2A40277E' \
  -H 'authority: be.testnet.vega.xyz' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'dnt: 1' \
  -H 'origin: http://localhost:3000' \
  -H 'referer: http://localhost:3000/' \
  -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
  --compressed
```

```json
{
  "transaction": {
    "block": "218488",
    "index": 2,
    "hash": "4D534CA14B04D37B62A6D3055332EC8DADB73B4DC10AF7631DDA601A2A40277E",
    "submitter": "846930eddecba90319ada7b920cf9f7ce48fa36d674561f2c2944ccb56a237ef",
    "type": "Batch Market Instructions",
    "code": 70,
    "cursor": "218488.2",
    "command": {
      "nonce": "6340433266930740930",
      "blockHeight": "218485",
      "batchMarketInstructions": {
        "cancellations": [
          {
            "orderId": "3c45500a9830206f25d16b2047146fb9c10af2fe3df4a738f5bb4b9fbe12299a",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "a68d0c4d7d648961d297f30cc431f6541e3eda5e1c151602cd59b4777d5b1a61",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "b9b835623a4cfbfdf438839481117058e4cd1c201a3e14f8ce16e8226b4fb1a5",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "0fe1daf588b6dd667d1763ba3e697d644b19fe48276d4d1afafabb9d8e876762",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "d8dfdfd147e70f028f379ade5ad08b4f035f1e35c8308fa17c72a8af813c9efa",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "a01433c3c3eb5e97656f315717d96e5d5ad2530bbe6302460cb8b234ebb28de2",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "6db76a29a8b03b66aec69fac2f3882866ddd4a4f6820b4eba3eb91e4375d0acb",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "050c027785f186ecebb4f9dc5d53f29445787cb8e34c797de3bffa535df80fec",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "16e6bb3b5e39643a915efdda11732c8af880ce6e354f0860dff3aeaf7aab2434",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "51d3c747a22787bf244f242ddbcf81b1b43fa9bd34f60ccbb5f6b0a6200e0d92",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "ff550289bbc047dd7ca916edaa902bc41e00af2ad0a465649a33215e2597b397",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "3a2212c4cb5bb9ea3ba794def7c65c6479ced42606c90a8969cac6d7d9704685",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "ab5c978536eb71182d854d786f2f4af661651a9513dab213a5416eba926e5dac",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "5bcf207873515514816aa577ea03cb87d90b7fae54964039bf8f8bec8b8f8ec3",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "647c9ed0de057acbb19160102eb1646140f7e265197f94a7ccf60e3f3accf41f",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "1d1f8861257100a92c2a322e01259e1a7285fc0f6d950b05eeb88dd9ded43ea3",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "6f393b576526419252acff022fa961d1e5f0f42be7cec50a4f6428a24bcd453f",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "a9ab10477bc40aa0f5a4d59c90ec14cf417778205cb115b0460a863e2b78f96f",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "eac1c5ca33b89f94a01ffc874321d6ea5dbb19f09ac54e30ce60fad9a1ea3012",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "b49b8134ec9001ebfe0be04b71d406044e9535e4ed4f32293f1f05db107f6a72",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "6d930b6280e73f3fb2e118fc0689afb09adf8162db21e20935bd1a0f7baebc47",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "359f134999908c0c0cba3ab6806bca0ccd39fe378f4df0d884ef7ac355260752",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "f0d1ccac71ec0808670f3d1bb082d54cb9abb3bb230c8111eaa8f1ffe4ed7510",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "7b7a07c8bc82fbdde1e12f87b0ee3832103552ad0c892130cd8619c712a996be",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "62b5a06f6480a2919ba9610633c3569325cbf6a5f2854ac5b8d3fb9cf75867dd",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "f4ab2af3f4a92432dc8e059312bb0f63a3f8af45b607cbaca6578560f5a7723b",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "42d2a12c479230080017912c256a01ad0a74d122ed4c43e6745dbd6cf19cfd36",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "2e2d436a9d8909a564666786688f7968a6103d28e40334fbe09774a2f4ce9bcb",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "ac790e51714c3625b558a3eec81d0944af0c2071840f7dcd523f51c13036f1d5",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "dd99f376e9bc33f32f04c9a9ee2483ec09ed9c8192e6f1c067be9944ece6cbd3",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "3207a93ff023d957312b4446cdb689aa9b5be8124b168d957e95fcfb74de609f",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "d2d4f7a86f34c3b451710a7c889370ea2de0d75ed347a92c42e6f49c7ce3a347",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "8e495ca63346781fe4c8a8cc92b98a77274ea9f0ca9be39e319348070d35149d",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "7128e2a6554a5f15a06f8a4634d54bf72d58f6464880b8f56e19ced855c51377",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "2a29d49db6dd4d9c4c9f8237da5e7b3149496c04862fa69a9d468b8f7b5a1f92",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "573d5a0365cf3ec7fef147c39d58a7f179c7e491193c0da53b18162b88cd22d2",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "0b24fbe02957e537c94612acd156d3945cc4710732af4a23fe943d4bac5a5bc2",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "e04487bcd16fe8346988cd38410df5553c0186472680e31cd7a2ffb95bd39113",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "e41574918b2a28037ddb9a485d18dfe91daaf4e636a73f38b23b235cf7a5fe2e",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "e73fb1f0d12676aaac9bb2cbd1bc8a7c4649fb51bfea57eb8d903e026385fc45",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "8c34a4e5d476a4a0f574fdc8048a9d2c0764cf229e5e7cff00c59529544cd54b",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "68f615081d30408ed75b901e856e5598c0878fcb531995c7734809ed8c7d8757",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "f8b1bb43ded0229668e01c35ed0f0aa84bc6f90b7ebb41dee3faceab5bbce0b0",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "df31b0da431a2ea8dcf131696f42b01517e1c7ba780b3dac8a023f956f9526c3",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "77cd1f125fb5f19bf8f6dc53c7c4136f4af52e5c2a58e64cdcd5c00516c64e40",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "5ddceacde27ebda8d0e3a5d77a1bcf491029abdb8bba709ada1a9a13646183c6",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "fa78630cb3a6923583181c7d13b98d209a560c60a649b2172ce140ea307a98dc",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "71b6ef67f70abd817754ae8de30ff6574d5dc19b476fe7ebc13acacf6caf945c",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "fab8895d04de47cd743e35dc659a812bc69677ce74c636ebd6ae420beacf9d41",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "6671844d95ea2b7f61c298984b25f03c018ec2df92ba82d3cdcfbafa20953d81",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "7dc6bc99fc9ca0fb312811df79e46fbf4e6c72e9a11589a2fdd1da891cd8e031",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "4f636082ddb170eb62dc0321ff1eb33f6b26ddf648837eae055f4b838afe44a7",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "79d6d4b79ac94929c09497241249936df6c2d3acb233bc4354af4386f78d3389",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "2f3022c02bae18cf111739e03f10c643478dc6adcd559a79cf8f516b36896a74",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "86e46eaec169f50a1759e9d3c7196bbb74355f95e2533a342c28d87268f49abe",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "e3af7f2028684c5d315e713af009279c7c465947cd8092e1e8788c479dfad2f5",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "0ee22833d1a4cb93041f16d2aaee8a547a2b2c802de750072a16841bf9126109",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "a9aed3164f28242050aa16c6c4724d08de5338702c7dad77a7f7e48a85a23397",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "264086baee864206ff8ce2ae461e1d835810a8c516f662437ce5a354073721e5",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "c1076a8da4d6040f694c207485c97e9875de17920783f59d6110ed9d4812f559",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "9ef73660bc5649e400e2f82bc01d663433fcc692790d1f4e5efa6cc4c363abda",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "f4c8926bb5050d7fa2410fab9a53d40b2cff5a9938ed9f71a20b489df363ea8e",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "4e1f3c4b08386a8ea0eefc20d7eaa2745877ebb2241560e460d6ee5591dce02c",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "0f55c39e6d577cbd47af8b11f877f6f7a2c589d5af8fc9d60fc9a97613cb49ea",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "dab301e7f2c4326deebc97d0c8f3263d057b3c13777ac36948664ce2ab737ac3",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "45848a592640750ec73140c4a508ce4a13c20e82521b2c0bdcf594baf9bd4e2f",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "aac9929089be659c5b68683accd50a0363d6e41160d9b4b967d322279ad3c074",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "538f3574de8cda10c36d29b9f9e717049416fb0fe2639c0799511f5bfeaf4809",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "e83fe07996b5f34087ff28b4796b82c7cf53132c20367fecfae9d84cf6ef79f1",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "f6de887f9cd7b8221a8835cb6b3ab789cb2a340c18b5cb9c5871e305528d48de",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "85a3ef52da4af9d8e66054cbf668f1dc461ebe6a0d62c5a63d84646c0c64a6db",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "3e4518732d2de912a048cc8e14a5091f492ca0a200c4f38d633b9864118322bb",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "b4c0e848ed486a5ab9762d4a87ec1fe9d334a2f4f3a0edb9c17dfcb4de0ab975",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "87f79ab5154c0ed40ebbfe47b6768dd5866272db144492c95b66975c6c8a7a75",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "7006b721ddedcbd1a57791dcab09b987344b89eeb5486bd95c5991e59d214a2e",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "6d365c8d9f9ef8b539570a2b960ed1f24e33364715cb9cdb3e4f59c41e240c06",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "bba54e82afccfb7ed7c4d8623f26a0d9183709d03b9baba812b71f74ab9e0e63",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "1e34b1585735379c6c2871d53313377376513eeed6dfc9a929d09fdc55811ec7",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "bc3c05664a22eab86bfeeac87b1118a675d5252387b45fec624e17886ee41320",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "0eca6a631c4d158184d737e554fa6dd8e95f53dd921b7db75cf7a3332ad19c8e",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "ba4ea66b3e4e63598701f8b740ef4407a6b07919433aef1149397771736b86ca",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "de55edea017a492890b901eacb3059c41a8d1a3fc2d1be797db6a50ab7b2135b",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          },
          {
            "orderId": "1881275cc868c9797716494d09ffaf6b74578ed2b481e7ec0e9b828a8af48d92",
            "marketId": "06cc8960d987cd4c7ba1364b7d849e5b92fd70267d2d1d91896b418951fe94a4"
          }
        ],
        "amendments": [
        ],
        "submissions": [
        ]
      }
    },
    "signature": {
      "value": "5f718d1fc1d42d79358f3c770ffdce9b25dd41182fada29773427132a304597ccd3e8b87b35f73351513ac326359acefffb1b26b7225ba0e6dc0fb0aee16200b",
      "algo": "vega/ed25519",
      "version": 1
    },
    "error": "0 (unable to find the order in the market), 1 (unable to find the order in the market), 10 (unable to find the order in the market), 11 (unable to find the order in the market), 12 (unable to find the order in the market), 13 (unable to find the order in the market), 14 (unable to find the order in the market), 15 (unable to find the order in the market), 16 (unable to find the order in the market), 17 (unable to find the order in the market), 18 (unable to find the order in the market), 19 (unable to find the order in the market), 2 (unable to find the order in the market), 20 (unable to find the order in the market), 21 (unable to find the order in the market), 22 (unable to find the order in the market), 23 (unable to find the order in the market), 24 (unable to find the order in the market), 25 (unable to find the order in the market), 26 (unable to find the order in the market), 27 (unable to find the order in the market), 28 (unable to find the order in the market), 29 (unable to find the order in the market), 3 (unable to find the order in the market), 30 (unable to find the order in the market), 31 (unable to find the order in the market), 32 (unable to find the order in the market), 33 (unable to find the order in the market), 34 (unable to find the order in the market), 35 (unable to find the order in the market), 36 (unable to find the order in the market), 37 (unable to find the order in the market), 38 (unable to find the order in the market), 39 (unable to find the order in the market), 4 (unable to find the order in the market), 40 (unable to find the order in the market), 5 (unable to find the order in the market), 6 (unable to find the order in the market), 7 (unable to find the order in the market), 8 (unable to find the order in the market), 9 (unable to find the order in the market)"
  }
}
```

**Comment by edd** [comment]
Dupe of https://github.com/vegaprotocol/vega/issues/7843

**Comment by barnabee** [comment]
I tried to update the original ticket to include this, but: this can be fulfilled by a new errors field outside of the "command" message, as long as any such field contains the metadata (index/location in batch, order reference, order ID) needed to associate the error with the instruction that caused it. We can accept “successful” being implied by nothing in the errors field referfencing a given instruction as long as it is **_guaranteed_** that the instruction succeeded in that case.
