### ISSUE TITLE
Data Source keys in GraphQL/REST: something is up

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#7286]
# Problem encountered
Something seems to be up with either the way Oracle Signers are represented in the API, or the way they are encoded when they are output. 

## Example 1
See Query 1 below - fetching the signers for a data spec via the market gives us a **Vega Key** of `0xfCEAdAFab14d46e20144F48824d0C09B1a03F2BC`, while querying for the signer by the oracle spec ID gives us `66434541644146616231346434366532303134344634383832346430433039423161303346324243`. This is wrong for a number of reasons:

1. The market was intended to be proposed as having an Ethereum based oracle with the address `0xfCEAdAFab14d46e20144F48824d0C09B1a03F2BC`
2. The signer key/address does not match when querying for the oracle on the market, or the oracle by ID
3. The shape of the GraphQL data is telling us that the key is a Vega Address, but neither option is a valid Vega key

#7283 was just merged, which was merged *before* this ticket was filed but *after* these markets were created. I've asked the market creator for the `newMarketProposal` so that we can diagnose if something was wrong with the proposal itself, which could be the cause of issue 1 above - where an ETH address is being treated as a Vega public key. But that would only partially explain the weirdness.

# Tasks
- [ ] Create a market with an External Data Source using an Ethereum Address as a signer
   - [ ] Ensure the GraphQL query below returns the correct Data Source type for the signer *on the market* as an `EthAddress` and that `Address` is correctly formatted)
   - [ ] Ensure the GraphQL query below returns the correct Data Source type for the signer *on the oracle by id* as an `EthAddress` and that `Address` is correctly formatted)
   - [ ] Ensure that the REST api returns the correct market signer type too
   - [ ] Ensure that the REST api returns the correct oracle signer also
- [ ] Create a market with an External Data Source using a Vega pubkey as a signer
   - [ ] Ensure the GraphQL query below returns the correct Data Source type for the signer *on the market* as an `PubKey` and that `Key` is correctly formatted)
   - [ ] Ensure the GraphQL query below returns the correct Data Source type for the signer *on the oracle by id* as an `PubKey` and that `Key` is correctly formatted)
   - [ ] Ensure that the REST api returns the correct market signer type too
   - [ ] Ensure that the REST api returns the correct oracle signer also

# Steps to reproduce
## Query 1: for a specific market by ID, and the oracle for that market by ID
```graphql
{
  marketsConnection(
    id: "41357a60fbb2aa09832742f07012250b3da4d87c38aa0f2e6bbd1391aec10d9f"
  ) {
    edges {
      node {
        id
        tradableInstrument {
          instrument {
            product {
              ... on Future {
                dataSourceSpecForSettlementData {
                  id
                  data {
                    sourceType {
                      ... on DataSourceDefinitionExternal {
                        sourceType {
                          ... on DataSourceSpecConfiguration {
                            signers {
                              signer {
                                ... on ETHAddress {
                                  address
                                }
                                ... on PubKey {
                                  key
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  oracleSpec(oracleSpecId:"ebbfea40bc2b3a7ea78392e30d419bfb48c88e92ba84425331e1b052dcad30d4") {
        dataSourceSpec {
          spec {
            data {
              sourceType {
                ... on DataSourceDefinitionExternal {
                  sourceType {
                    ... on DataSourceSpecConfiguration {
                      signers {
                        signer {
                          ... on ETHAddress {
                            address
                          }
                          ... on PubKey {
                            key
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
}
```

### Result for query 1
```json
{
  "data": {
    "marketsConnection": {
      "edges": [
        {
          "node": {
            "id": "41357a60fbb2aa09832742f07012250b3da4d87c38aa0f2e6bbd1391aec10d9f",
            "tradableInstrument": {
              "instrument": {
                "product": {
                  "dataSourceSpecForSettlementData": {
                    "id": "ebbfea40bc2b3a7ea78392e30d419bfb48c88e92ba84425331e1b052dcad30d4",
                    "data": {
                      "sourceType": {
                        "sourceType": {
                          "signers": [
                            {
                              "signer": {
                                "key": "0xfCEAdAFab14d46e20144F48824d0C09B1a03F2BC"
                              }
                            }
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      ]
    },
    "oracleSpec": {
      "dataSourceSpec": {
        "spec": {
          "data": {
            "sourceType": {
              "sourceType": {
                "signers": [
                  {
                    "signer": {
                      "key": "66434541644146616231346434366532303134344634383832346430433039423161303346324243"
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by daunatv** [comment]
The proposal used for creating the market `41357a60fbb2aa09832742f07012250b3da4d87c38aa0f2e6bbd1391aec10d9f` was the following script.

`proposal = {
       "proposalSubmission": {
      "reference": "injected_at_runtime",
      "rationale": {
        "description": "ETH USDT-TII",
        "title":"ETH USDT-TII"
      },
      "terms": {
        "closingTimestamp": 1673030104,
        "enactmentTimestamp": 1673030174,
        #blockchain_time_seconds + 1000,
        #blockchain_time_seconds + 1040,
        #"validationTimestamp": blockchain_time_seconds + 1,
        "newMarket": {
          #"marketId":"58bd4a33d03a7827a74a45a03218c045d76eda0bc8db9ae240f2f6fc35c1d102",
          "changes": {
            #"lp_price_range": "0",
            "instrument": {
              "name": "ETH USDT-TII",
              "code": "ETHUSDT-TII",
              "future": {
                "settlementAsset": "373d90d97bd3f97f0c13cf449926cfd7f1ed5f3746c3091e8dd894d60bf5eac8",
                "quoteName": "USD",
                #"settlementDataDecimals": 6,
                #"lpPriceRange": "0.05",
                "dataSourceSpecForSettlementData": {
                  #"id": "100",
                  #"data": {
                    "external": {
                      "oracle": {
                        "signers": [
                          {
                            "pubKey": {
                              "key": "0xfCEAdAFab14d46e20144F48824d0C09B1a03F2BC"                         
                              }
                            
                          }
                        ],
                        "filters": [
                          {
                            "key": {
                              "name": "prices.ETH.value",
                              "type": "TYPE_INTEGER",
                              "numberDecimalPlaces": "6"
                            },
                            "conditions": [
                            {
                            "operator": "OPERATOR_GREATER_THAN",
                            "value": "0"
                            }
                            ]
                          }
                        ]
                      }
                    }
                  #}
                  },
                 "dataSourceSpecForTradingTermination": {
                  #"data": {
                    "external": {
                      "oracle": {
                        "signers": [
                          {
                            "pubKey": {
                              "key": "69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f"
                            }
                          }
                        ],
                        "filters": [
                          {
                            "key": {
                              "name": "trading.terminated.ETHUSDT-TII",
                              "type": "TYPE_BOOLEAN",
                              
                              #"numberDecimalPlaces": "6"
                              #"settlement_data_decimals": 6,
                            },
                            "conditions": [
                            {
                            "operator": "OPERATOR_EQUALS",
                            "value": "true"
                            }
                            ]
                          }
                        ]
                      }
                    }
                  #}
                  },
                "dataSourceSpecBinding": {
                  "settlementDataProperty": "prices.ETH.value",
                  "tradingTerminationProperty": "trading.terminated.ETHUSDT-TII"
                }
              }
            },
            "decimalPlaces": 2,
            "positionDecimalPlaces": 2,
            "lp_price_range": "0.05",
            "metadata": [
							"formerly:4BC6D2154BE74E1F",
							"base:ETH",
							"quote:USDT-TII",
							"class:fx/crypto",
							"monthly",
							"sector:defi",
              "settlement-expiry-date:2023-01-10T10:00:00.000Z"
       
            ],
            "priceMonitoringParameters": {
              "triggers": [
                {
                  "horizon": 43200,
                  "probability": "0.9999999",
                  "auctionExtension": 300
                }
              ]
            },
            "liquidityMonitoringParameters": {
              "targetStakeParameters": {
                "timeWindow": 3600,
                "scalingFactor": 10
              },
              "triggeringRatio": "0.3",
              "auctionExtension": 1
            },
            "logNormal": {
              "riskAversionParameter": 0.001,
              "tau": 0.0001140771161,
              "params": {
                "mu": 0,
                "r": 0.0,
                "sigma": 1.5
              }
            }
          },
        }
      }
    
    },
    "pubKey": pubkey,
    "propagate": True
}`

**Comment by edd** [comment]
Note that in the above, the signer is specified as:

```json
   "oracle": {
      "signers": [
        {
          "pubKey": {
            "key": "0xfCEAdAFab14d46e20144F48824d0C09B1a03F2BC"                         
            }
          
        }
      ],
```

Which, if you are looking at the GraphQL query above, looks incorrect - an `EthAddress` type of signer should have a property called `address`, not `key`. **HOWEVER**! This proposal has been used successfully to settle markets with Open Oracle signed message data from `0xfCEAdAFab14d46e20144F48824d0C09B1a03F2BC`. So while it is possible that the proposal *should* use `address` instead of key, the core is correctly mapping the data.

**Comment by jeremyletang** [comment]
Alright I've just check in the database, and the specs are save with signers expecting vega pubkey, while these are eth addresses.
