### ISSUE TITLE
Add block interval type

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#7288]
# Feature Overview

**In order to** View hloc data for a single block
**We will** add block height as a special interval type
**So that** candles can be grouped by block height

# Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios. Ideally, tasks would reflect the issues/pull requests likely to be created when developing the feature. 
- [ ] Add INTERVAL_BLOCK
- [ ] Allow INTERVAL_BLOCK to be used for candlesConnection
- [ ] Allow INTERVAL_BLOCK to be used for the candles subscription 

# Acceptance Criteria
- I can query for candles by block interval
- I can subscribe to candles by block interval
