### ISSUE TITLE
Set Access-Control-Max-Age for OPTIONS responses

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#7349]
# Feature Overview

**In order to** avoid clients having to send as many PREFLIGHT requests as they currently do
**We will** set `Access-Control-Max-Age` to `7200` for all `OPTIONS` queries (to graphql & rest endpoints)
**So that** browsers will cache OPTIONS as effectively as possible

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age - and https://developer.mozilla.org/en-US/docs/Glossary/preflight_request for more about OPTIONS/preflights

Current default: OPTIONS responses expire after 5 seconds, so will be sent on the next query after that.

# Tasks
- [ ] Make GraphQL respond with the appropriate header and value to all OPTIONS requests to the query endpoint
- [ ] Ensure REST does the same
- [ ] Ensure Block Explorer does the same
