### ISSUE TITLE
Block Explorer API filter by transaction type

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#7386]
# Feature Overview

**In order to** allow users to quickly find specific transactions
**We will** Add a new filter to the transaction list endpoint
**So that** API users can filter by submitter as well as transaction type

https://github.com/vegaprotocol/vega/blob/05be47e2442e5bea16c43579710a5591b73e12c8/blockexplorer/store/transactions.go#L81-L87

# Tasks
- [ ] Add `tx[type]` to filters list
- [ ] Allow filtering by once specific type (e.g. `tx[type]=OrderSubmit`)
- [ ] Allow filtering by multiple types at once
