### ISSUE TITLE
More advanced Market query filtering API

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#7481]
# Feature Overview

**In order to** (context - overcome a problem or meet a requirement)
**We will** (what - carry out this piece of work / action)
**So that** (why - we create these outcomes)

#7425 added a boolean filter allowing queries to *exclude* settled markets:

```graphql
{markets(includeSettled=false){data{..}}}
```

This defaults to true, so the old behaviour is retained. Instead of a boolean, it would be great to be able to provide a list of market statuses. 

```graphql
marketsConnection(filter:{
  state: [STATE_ACTIVE,STATE_PENDING]
  tradingMode:[...]
}) {
  # ... only active and pending markets
}


# Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios. Ideally, tasks would reflect the issues/pull requests likely to be created when developing the feature. 
- [ ] Add `state` filter, accepting a list of [`MarketState`](https://github.com/vegaprotocol/vega/blob/develop/datanode/gateway/graphql/schema.graphql#L2973-L2998)
- [ ] Add `tradingMode` filter, accepting a list of [`MarketTradingMode`](https://github.com/vegaprotocol/vega/blob/develop/datanode/gateway/graphql/schema.graphql#L3001-L3016)
- [ ] Mark `includeSettled` as `@deprecated`

# Acceptance Criteria
- It is possible to fetch a list of [`STATE_ACTIVE`], [`TRADING_MODE_CONTINUOUS`] markets via GraphQL & REST
  - This should return all markets that are active and trading
- It is possible to list [`STATE_TRADING_TERMINATED`, `STATE_SETTLED`] via GraphQL & REST
  - This should return all markets that are terminated or settled
