### ISSUE TITLE
The `EstimateFee` API docs needs a full review

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7991]
### Issue

The `EstimateFee` API docs needs a full review 

see:
- https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-estimate-fee
- https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-estimate-margin

### Tasks:

- [ ] There is usage of “this order” when the query parameters are not that of a Vega order object. This should be reviewed and corrected
- [ ] There ate parentheses everywhere - do we really need all these? These should be reviewed and corrected
- [ ] There is a description that states "when submitting", this is incorrect and should be "when trades"... Needs an overhaul and tidy up.

**Comment by jeremyletang** [comment]
Just doing the estiamtes fee part for now as the estimate margins is being reworked.
