### ISSUE TITLE
Review validation on all command inputs

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8004]
### Issue

There was a mainnet incident that caused an outage whereby there was insufficient validation on the Tendermint public keys specified in the `announce node` command, when this validator was promoted to become a consensus validator it caused a panic.

We need to review ALL the command inputs and ensure that we have sufficient validation to ensure that malformed data is not input. 

**Tasks**

- [ ] Review all command inputs and ensure there is validation
- [ ] Identify where validation exists if this can be enhanced
- [ ] Test (fuzzing inputs?) to ensure that malformed inputs when submitting a transaction command do not cause network issues/outages

**Comment by wwestgarth** [comment]
Ethereum address validation could be tightened up. We use this function to convert ethereum address to a canonical form:
```
// EthereumChecksumAddress is a simple utility function
// to ensure all ethereum addresses used in vega are checksumed
// this expects a hex encoded string.
func EthereumChecksumAddress(s string) string {
	// as per docs the Hex method return EIP-55 compliant hex strings
	return common.HexToAddress(s).Hex()
}
```

but we do not check it is a hex string first. So if pass in hello I get the null address:
```
EthereumChecksumAddress("hello") -> 0x0000000000000000000000000000000000000000
```

I would expect some `checkTx` error on commands that pass in a eth address (eg. announce node, issue signatures, withdrawals) rather than using `0x0000000000000000000000000000000000000000`.

**Comment by wwestgarth** [comment]
Talking with @jgsbennett we've identified the following areas to target:
- Submitting nonsense strings in things that take in strings: things like `\n` or massive strings filled with spaces
- Sending in nonsense valiator commands: nodeVotes for things that don't exist etc the reasoning being validator commands skip the spam/pow engine and the bar to entry is just announcing yourself into a pending state
- Amending orders and market proposals: they have complicated validation with lots of fields, so its worth spending some time with them

**Comment by gordsport** [comment]
Closing as this issue has uncovered a number of areas that have needed attention. These have been resolved.
