### ISSUE TITLE
Inconsistent REST titles and ordering

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8024]
### Issue

The way the REST titles are written is very inconsistent:

**There are differences in capitalisation:**
- Market data history
- Market Data

**There are some outliers that do not conform at all to any kind of consistent formatting:**
- Transfer Responses: it’s a subscription, every other subscription is a Blah Blah subscription
- Trade (latest): why the latest?
- Balances -> BalanceChanges list

**Ideally the text should match the RPC endpoints and have the titles like:**
- “List Deposits” instead of “Deposits list”
- “Get Deposit” instead of “Deposit”
(before updating this see the first task below regarding how the docs are being ordered)

### Tasks

- [ ] Review the tools used for auto-generating the docs with @edd to understand how the docs are ordered
- [ ] If ordering or grouping is possible review these options and decide on how we can group (if thats possible/best)
- [ ] Make the REST titles consistent and ordered/grouped to make navigating the docs as easy as possible
