### ISSUE TITLE
[API]: Add `fee` to transfers objects in GraphQL & REST

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#8056]
>[!WARNING]
> Reopened as it is not possible in GraphQL to get the fee for an individual transfer

https://github.com/vegaprotocol/vega/blob/develop/datanode/gateway/graphql/schema.graphql#L718-L755

In GraphQL and REST, it is not possible to know what they fee paid for a transfer is. You can *guess* by looking at a network parameter, but that is unreliable for transfers in the past as the factor could have changed.

# Changes
- A new field should represent the fee paid for a transfer
- The fee should be the value in the same asset as the transfer
- The fee should not be the fee factor, but the actual amount paid for the transfer

# Tasks
- [ ] https://github.com/vegaprotocol/vega/issues/8056#issuecomment-1853673347
- [x] Expose `fee` in GraphQL
- [x] Expose `fee` in REST
- [ ] Either:
    - [x] Recurring transfers should contain an array of fee objects containing the individual fees paid, and the date and time of each
    - [ ] Recurring transfers should contain a total of the fees paid to date

**Comment by edd** [comment]
In GraphQL, the fees are not exposed by the `{ transfer(id:"123"){...} }` query. They are exposed by `{ transfersConnection(partyId:"456"){...} }`, but the `trransfersConnection` query does not support selecting by ID

# Tasks
- [ ] Add `fees` to `query { transfer(){ ... } } }` response in GraphQL
