### ISSUE TITLE
Remove all the offset pagination

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8093]
### Issue

During a recent issue to tidy up the API documentations it was noted that endpoints like this one is have both cursor and offset based pagination
- https://github.com/vegaprotocol/vega/issues/7989

Its been decided that all offset pagination should be removed.

### Tasks

- [ ] Remove all offset pagination
- [ ] Update all affected API docs in the /vega repo
- [ ] Update the docs site where and if applicable based on this change (cc @candida-d ) e.g., this [PR](https://github.com/vegaprotocol/documentation/pull/548/files#diff-3ba03f23a417a0fa7a69d91e40ecc278f69fefc087a864af00d0dd5472aac226R119)
