### ISSUE TITLE
Spots governance

### ISSUE THREAD

**Issue by ze97286** [vegaprotocol/vega#8117]
# Feature Overview

To be able to create a spot market proposal need to add spot market definitions and implement support in governance engine. The protos include the following:
* New spot market proposal
* Spot product
* Liquidity commitment

## Specs
- [[Spot spec](https://github.com/vegaprotocol/specs/blob/3ad0facad09ca18f225a2144b67d6b138ea46f7c/protocol/0080-SPOT-product_builtin_spot.md)](Spot spec WIP) 

# Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios. Ideally, tasks would reflect the issues/pull requests likely to be created when developing the feature. 
- [x] Add proto definitions for spots market
- [x] Add spot market creation to governance engine 
- [x] Add spot market update to governance engine 

# Acceptance Criteria
TBD
