### ISSUE TITLE
Add withdrawals to checkpoint data

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#8218]
# Feature Overview

**In order to** avoid users potentially losing their money forever during a network crash 
**We will** add the signature bundles for any withdrawal that is not yet finalised on ethereum to the checkpoint data
**So that** users do not lose their funds forever in the event of a crash and get VERY angry with us 

## Specs
- Not required 

# Tasks

- [ ] Store the signature bundle for any withdrawal which does not yet have a tx hash from ethereum to the checkpoint
- [ ] Be able to restore those signature bundles after a restart

# Acceptance Criteria

- It is possible to store the signature bundles to the checkpoint 
- It is possible to complete a withdrawal on ethereum after a network crash and checkpoint restart

# Test Scenarios

GIVEN I create a withdrawal and approve it in my vega wallet but do not yet complete it on ethereum (ie. it has `status_finalised` but `tx_hash` is `null`)
WHEN there is a checkpoint restart 
THEN I am still able after the restart to complete my withdrawal on ethereum using either the UIs or the ERC20 contract directly

# Additional Details (optional)
None

# Examples (optional)
None

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Create relevant for [system-test](https://github.com/vegaprotocol/system-tests/issues) tickets with feature labels
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All acceptance criteria confirmed to be met, or, reasons why not discussed with the engineering leadership team
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new system-tests
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature
