### ISSUE TITLE
[EPIC]: Hybrid/passive liquidity

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8228]
### Feature breakdown: Hybrid/passive liquidity

In order to kick off work on Hybrid/passive liquidity we need to:

- [ ] form a core sub team to work on this feature (core+qa)
- [ ] review information from the kick off meeting and the spec
- [ ] break the work down into deliverable (sprint-sized) testable work items
- [ ] ensure that both ACs are covered in the specs and issues raised for QA testing

#### Spec

- [Offbook liquidity sources: step 1 towards "passive" liquidity](https://github.com/vegaprotocol/specs/issues/1150)
- [Passive Liquidity, maybe with CFM-based AMMs](https://github.com/vegaprotocol/specs/issues/1990)
