### ISSUE TITLE
Create governance proposal for successor markets

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8259]
# Feature Overview

In order for users to create a successor market we need a specific governance proposal.

## Specs
- [Spec Issue and linked PR](https://github.com/vegaprotocol/specs/issues/1440)

## Tasks
- [ ] Create a specific proposal for successor market
- [ ] Extend protos to enable work on commands (and the validations) and data node APIs (discuss with the front end team)
- [ ] Validation on proposals to ensure a market has only one child (this needs to check/account for other proposals enacted  since the governance proposal in question)
- [ ] Error handing
