### ISSUE TITLE
Update collateral engine for successor markets (insurance pool management)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8263]
# Feature Overview

In order for the insurance pool(s) to be managed when a market has a successor we need to update the collateral engine, have data node store the new events and expose these (where applicable).

## Specs
- [Spec Issue and linked PR](https://github.com/vegaprotocol/specs/issues/1440)

## Tasks
- [ ] Insurance pool management - new transfer types and events as an insurance pool will outlive its market (carries over to succeeded market)
- [ ] Data node - consume these new events and best store and expose this data (engage with front end teams)

## Questions:
- [ ] Regarding querying the balance of an insurance pool, do we need an API for this? - how its distributed x-parent/child markets

**Comment by gordsport** [comment]
This has been implemented in an existing successor market PR therefore can be considered done
