### ISSUE TITLE
[Feature]: CLI Wallet Legal Disclaimer

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega#8283]
## Story

As a CLI Wallet team
We want our users to fully understand what the app allows them to do and the risks involved   
So that all users can make an informed decision on whether or not they wish to accept the risks and use the app

## Acceptance Criteria

When I open the CLI Wallet for the first time...
- [ ] I am provided with brief legal disclaimer describing what the app does and the risks involved 
- [ ] I can acknowledge the disclaimer and continue to the CLI wallet
- [ ] I can not continue to use the CLI wallet without acknowledging the disclaimer
- [ ] I am provided with relevant information based on the network I am connected to (i.e. different message for mainnet v testnet) 

## Tasks

- [ ] Implement
- [ ] Write unit tests
- [ ] Write end to end tests
- [ ] Code review
- [ ] Verify acceptance criteria met
- [ ] Exploratory QA testing (capturing bugs and new edge cases in this or new tickets) 
- [ ] Write automated regression tests for the A/Cs (expanding on A/Cs where possible) 
- [ ] Release

## Notes

[Mainnet content has been drafted by legal here](https://docs.google.com/document/d/1bg7dKCbV-HRgf8Jof7W_guD1JcO0nbl36hSVJ0CObUQ/edit)

**Comment by gordsport** [comment]
Top avoid a breaking change can we have e a subcommand, something like: `vegawallet terms` that displays the terms to the users
