### ISSUE TITLE
[Feature]: Terminate/Suspend market

### ISSUE THREAD

**Issue by ze97286** [vegaprotocol/vega#8415]
# Feature Overview

**In order to** terminate a spot market or suspend/resume any market a governance proposal is required. 
**We will** create a new governance proposal for terminating/suspending/resuming a market. 
**So that** a spot market can be terminated and any market can be suspended and resumed. 

## Specs
- https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0028-GOVE-governance.md#6-change-market-state

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] Implement the governance proposal 
- [ ] Implement the market termination for spots
- [ ] Implement the market suspend for any market
- [ ] Implement the market resume for any market
