### ISSUE TITLE
[Feature]: Fetch proposals for successor markets (wip)

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#8439]
# Feature Overview

**In order to** indicate to a user that a successor market has been *proposed*
**We will** add a new API endpoint to explorer successor market proposals
**So that** there is a way for API clients to know that there are proposals related to the current market

## Background
When Successor Market APIs are merged, there will be an API that will be able to tell us:
* If a given market ID has a successor market
* Given a market ID, what the markets predecessor was

This covers the most important use case already. 

For Block Explorer, it would be interesting to get some extra information related to proposals for successor markets, *whether or not they succeeded or were rejected*.

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] For GRPC, REST and GraphQL
  - [ ] Add a new API endpoint that takes one parameter - a market ID
  - [ ] That parameter returns a list of proposals
    - [ ] All of those proposals will reference the provided market ID as the market they succeed

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN I am 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.
