### ISSUE TITLE
Stop orders snapshots

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#8470]
Implement snapshot states for stop orders:

```[tasklist]
### Tasks
- [ ] add snapshots for trailing stop orders
- [ ] add snapshots for priced stop orders
- [ ] ensure submission ordering.
```
