### ISSUE TITLE
[Feature]: A party with no governance token, but sufficient ELS should be able to submit a market change proposal

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/vega#8527]
## Issue

The following PR in the specs repo describes the changes required for a party with no governance token, but sufficient ELS, being able to submit a market change proposal. 

- https://github.com/vegaprotocol/specs/pull/1768

### Tasks

- [ ] Review the spec change and asses the work required in core
- [ ] Ticket the items required for core/data node
- [ ] Discuss with the front end governance team the proposed tickets on the core side (cc @mattrussell36 / @pennyandrews )

**Comment by jeremyletang** [comment]
this is implemented.
