### ISSUE TITLE
Add market closure governance proposal - feature review and breakdown

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8558]
## Issue

The following PR in the specs repo describes the changes required for adding a market closure governance proposal. I some cases a market may need action from the community via a governance vote to close the market.

- https://github.com/vegaprotocol/specs/pull/1614

### Tasks

- [ ] Review the spec change and asses the work required in core
- [ ] Ticket the items required for core/data node
- [ ] Discuss with the front end governance team the proposed tickets on the core side (cc @mattrussell36 / @pennyandrews )
