### ISSUE TITLE
Filter proposal by type and status

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vega#8564]
## Chore

In the governance dapp front end we currently do two things when it comes to grouping proposals

1.  filter out rejected proposals from the proposals returned by this API [ ] onto a separate page so that community members looking to vote are not distracted by irrelevant past attempts
2. group proposals by open or closed (declined, enacted, failed, passed, rejected, node vote)

Right now there is no pagination of open, closed or rejected proposals, which is giving us performance / loading issues. In order to paginate the proposals with the existing API we would need to revert to showing all proposals in one list, without any grouping or  way to filter the by type or status, making it harder to find the proposals we want people to vote on.

This chore is to create API endpoints for proposal type: 
* New market 
* Update market 
* Network parameter 
* New asset
* Update asset
* Freeform 

And for status 
* Declined
* Enacted 
* Failed 
* Open 
* Passed 
* Rejected 
* Node vote

## Acceptance Criteria

- [ ] I can request a list of proposals by type
- [ ] I can request a list of proposals by status
- [ ] I can still request a list of all proposals
- [ ] Frontend can paginate an ordered list of proposals

## Tasks

- [ ] UX (if needed)
- [ ] Design (if needed)
- [ ] Team and stakeholder review
- [ ] Specs reviewed and created or adjusted
- [ ] Implementation
- [ ] Testing (unit and/or e2e)
- [ ] Code review
- [ ] QA review

**Comment by JonRay15** [comment]
Sam says this is actually now delivered ... somehow. Dunno when. 😂
