### ISSUE TITLE
[Feature breakdown]: Referral program

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8797]
# Feature Overview

**In order to** help the network drive growth
**We will** develop an on chain referral program

## Specs
- https://github.com/vegaprotocol/specs/issues/1669

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] review the spec
- [ ] break down the feature into issues
- [ ] label all issues with the `referral` label
