### ISSUE TITLE
[Feature]: Enable more/custom intervals in charts

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega#8867]
# Feature Overview

As a Console user 
I want to be able to view chart data in a wider range of intervals / any interval I want
So that I can analyse data in a way the works for me and my trading

You can currently only choose between the following intervals on the charts:
<img width="391" alt="Screenshot 2023-07-14 at 14 45 02" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/8c866e3c-ef04-47a4-b5b6-cda220baa65e">

Frontend would need the API to be extended to be able to support this functionality.

## Acceptance Criteria

- [ ] I can select a preset interval to view chart data in 30m intervals
- [ ] I can select a preset interval to view chart data in 2H intervals
- [ ] I can select a preset interval to view chart data in 4H intervals
- [ ] I can select a preset interval to view chart data in 12H intervals
- [ ] I can select a preset interval to view chart data in 3D intervals (nice to have)
- [ ] I can select a preset interval to view chart data in 1W intervals (nice to have)
- [ ] I can select a preset interval to view chart data in 1M intervals (nice to have)
- [ ] I can specify a custom interval to view chart data (i.e. by specifying a number and a unit) 

Barney "The ideal state is that candle and aggregation APIs on data node all take any number plus unit (tick/block/second/minute/hour/day/week/month/year), so we can offer "presets" plus a custom option."

## Specs
- [Link](xyz) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ]
- [ ]

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.
