### ISSUE TITLE
[GLS-012] Input validation: Using a Unicode character in a Wallet API request header triggers an internal error

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8934]
## Issue

During a Sending a unicode character inside of the request header makes it possible to trigger an internal error. While returning a declined request message to the requester, the wallet presents a permissions request to the user.

Example:

`curl -L -X POST 'http://localhost:1789/api/v2/requests' -H 'Origin: 💣' -H 'Authorization: VWT 123' -H 'Content-Type: application/json-rpc' -H 'Accept: application/json-rpc' --data-raw "{"id": "1","jsonrpc": "2.0","method": "client.connect_wallet","params": [] }"`

After rejecting the wallet question, an error message appears:

`! An internal error occurred: reviewing the wallet connection failed: the trace IDs between the request and the response mismatch: expected "ZEBVw7XxrjFNXFwCaGB9GbEoPsOS20iZwF30OOerSkrI42goPMfDy4pqn5InbGrC", got "onjLbbBDnOnHzpAWljKuwhAysLDD60Ne6VHBHfchD2LNTE5NhDJd2Xhc6CdvZwTA" ! The request has been canceled.`

It is likely possible to send multiples of these requests triggering the internal error. This error then returns on each subsequent request, even without the added unicode characters. The exact impact of this is unknown, however, it constitutes undesirable behaviour and is thus deemed a potential security risk.

## Tasks:

- [ ] Review this and see if this poses a security risk - we do not think so at this time
- [ ] Decide if this is a CLI wallet issue or more related to DT/Browser wallet 
- [ ] If a security risk we need to plan to get this scheduled asap

cc @dexturr @JonRay15
