### ISSUE TITLE
[Feature]: Make the ledger entry CSV export more human readable

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8946]
# Feature Overview

**In order to** make the CSV export more user friendly when looking at asset details  
**We will** discuss the impact of resolving the asset ID to display the asset name and to convert the asset values to human readable values with decimal places as per what is specified by the asset
**So that** we can mitigate users having to do post processing of the data and having to find the asset details themselves 

## Tasks
- [ ] Review the request and understand what performance impact adding this would cause
- [ ] feedback the perceived performance changes
- [ ] Align with @vegaprotocol/frontend in case of any changes required to the console
- [ ] Implement and test
