### ISSUE TITLE
[Feature]: Clean up epochs API for validator scoring

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9014]
# Feature Overview

**In order to** clean up the validator scoring screen on the governance app
**We will** add some additional content to the rewardScores part of the epochs API
**So that** we can give a clearer picture to users and remove some tech debt in the Governance App

## Specs
- [Link](xyz) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] Review the example of the current output as shown below
- [ ] Review the background I've provided below as rationale
- [ ] Add `theoreticalStakeScore` (or just call it `stakeScore`?) to the `rewardScore` section of the API as defined below
- [ ] Add `stakedTotalForScoring` to the `rewardScore` section of the API, where that is the stake from the previous epoch which was used to calculate scores - which will be different to the current `stakedTotal` on the API probably
- [ ] Rename `rawValidatorScore` to `antiWhaledStakeScore` so it is more reflective of what it is

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Example of the current output that is provided.

There are two main issues with this data:
1. Some of it comes from current epoch (stakedTotal etc) while the reward scores have all been calculated based on data from the epoch prior.  This makes it hard to make logical comparisons and draw logical conclusions in the front end.
2. A critical piece of information is missing from the rewardScore section; Zohar described this as the "Theoretical Stake Score" of each validator.  This is basically `stake / total stake of validators of that type`.  Once you have this the other scores make more sense because then `rawValidatorScore` is that score minus anti-whaling, `validatorScore` then included performance penalties, and finally `normalisedScore` is those scores all normalised out.

<img width="467" alt="image" src="https://github.com/vegaprotocol/vega/assets/89918817/fd99a338-10a4-4f1a-9e76-5b05ed060c41">
