### ISSUE TITLE
[Feature]: Make CLI wallet respond to console faster

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9192]
## The Chore

When console (or governance app) checks with the wallet to find out the network currently it whirs around for quite a long time.  This is because Console sends a request to the wallet to ask what chain ID it is on, then the wallet sends requests to datanodes to ask this.  If a few datanodes are needed it takes a while. 

This shouldnt be taking this long because the wallet should already know which chain it is on when it boots up.  Therefore it should be able to respond instantly.

## Tasks

- [ ] Make sure the CLI wallet (and therefor browser wallet) is caching the chain ID its on when it starts up 
- [ ] Make sure it can provide this to Console instantly
- [ ] Confirm in tests that Console is now fast
- [ ] Confirm this also works for Browser wallet
