### ISSUE TITLE
[Feature]: Add transaction ID to orders returned by API

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#9221]
# Feature Overview

**In order to** link between client applications and the block explorer
**We will** add a transaction ID field to Orders
**So that** we can determine which transaction created an order

## Tasks
- [ ] In REST, the `Order` object should have a new `txId` field that contains a transaction ID
- [ ] In GraphQL, the `Order` object should have a new `txId` field that contains a transaction ID
- [ ] In both cases, the `txId` field should contain the hash of the transaction that created the order

## Feature test scenarios

GIVEN a `submitOrder` TX with a hash of `0497b51e5b30694edc1b031bad4c6165a925b270da16445eade20cce5522fad0`
AND that `submitOrder` creates a order with the deterministic ID of `49acf2f39ebbe92d708c313138dab3b70180b42a33e420db8553536fee2fab07`
WHEN I hit the [Get Order REST endpoint](https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-get-order)
THEN the Order should be returned
AND that order should contain a field called `txId`
And that `txId` field should contain `0497b51e5b30694edc1b031bad4c6165a925b270da16445eade20cce5522fad0`

**Comment by wwestgarth** [comment]
@edd can you add some notes on the your workflow that needs this new field please?

**Comment by edd** [comment]
Extra questions from Slack:
> like what about orders that are triggered from a stop-order?
The `stopOrdersSubmission` tx ID. 

The stop orders API has a layer of abstraction, in that a `stopOrdersSubmission` creates two `stop orders`, which (if triggered) create orders. The transaction that creates the order is thus the `stopOrderSubmission`.

> or network orders when someone gets closed out, what txID would we expect there? 
There is no transaction that triggers this, so the field would have to be nullable. You could debate that the order that triggers a market move that triggers a margin closeout is the transaction that creates it, but there is no sensible world in which someone else's order TX is returned by this field. 

The order that is stopped would have the TXID set to the `OrderSubmission` that created it. The order that trades with it would have a null TXID.

**Comment by daunatv** [comment]
So tested out stop orders OCO and when doing that I tried  to check the order that had been triggered, but not able to find anything using the order id in the explorer which made it a bit confusing.

`13d3ab522dbc712a414dc4c114dd16674e3dd4b14da929433647de43ecb82681`

<img width="1182" alt="Screenshot 2023-08-31 at 17 41 05" src="https://github.com/vegaprotocol/vega/assets/100769129/adc22c5b-7994-426c-8e4c-99d4260dd209">

<img width="516" alt="Screenshot 2023-08-31 at 17 41 11" src="https://github.com/vegaprotocol/vega/assets/100769129/09e13766-71c3-4d95-926a-c349c5e31f2a">
