### ISSUE TITLE
[Feature]: Enhance trade API for volume and referral discounts

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9254]
# Feature Overview

**In order to** support front end 
**We will** enhance the **trade API**
**So that** front end can:
- Display the volume discounts applied in console on the fills table
- Display the referral discounts applied in console on the fills table

## Specs
https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0084-VDPR-volume_discount_program.md

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.

Enhance the trade API to include:
- [ ] Amount discounted due to volume discount:
  - [ ] infrastructure_fee_volume_discount
  - [ ] liquidity_fee_volume_discount
  - [ ] maker_fee_volume_discount
- [ ] Amount discounted due to referrer discount
  - [ ] infrastructure_fee_referral_discount
  - [ ] liquidity_fee_referral_discount
  - [ ] maker_fee_referral_discount

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.

**Comment by ze97286** [comment]
closed by #9278
