### ISSUE TITLE
[Feature]: Game summary API

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9256]
# Feature Overview

**In order to** support front end
**We will** build a NEW game / competition summary API 
**So that** front end can:
- In combination with #9257 build the competitions view on page 8 of the wireframes

## Specs
- [Link](xyz) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] Create a new API for the "game" summary information
- [ ] API should update at the end of every epoch
- [ ] A "game" is defined by the reward pool hash (which may be fed by multiple recurring transfers)
- [ ] Any recurring transfer with a dispatch metric should be regarded as a "game / competition / reward scheme" and included in this

This game summary needs to include all the below for each game
- [x] Status (Active / Finished)
- [x] Start epoch
- [ ] End epoch
- [ ] Window length
- [ ] Lock period (added 24/10) 
- [ ] Type (reward metric)
- [ ] Total reward payment each epoch
- [ ] Number of participants (as at end of each epoch)
  - [ ] Number of entities participating (individuals & teams)
  - [ ] Number of entities paid (individuals & teams)
- [ ] Eligibility requirements
  - [ ] Notional time weighted position required
  - [ ] Stake required

Filtering requirements
  - [ ] By reward pool hash 
  - [ ] By epoch

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.

**Comment by dexturr** [comment]
Eligibility requirement I see there is `minimum epochs in team` in the spec. Is this required to be shown and should also be exposed here?

**Comment by JonRay15** [comment]
We have now covered all this view either the enhancements to transfers API or this new game details ticket.

https://github.com/vegaprotocol/vega/issues/9257
