### ISSUE TITLE
[Feature]: Party reward & referral factors

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9258]
# Feature Overview

**In order to** support front end
**We will** build a NEW party reward & referral factors API 
**So that** front end can build:
- The team member details on page 6 of the wireframes
- The profile information on page 11 of the wireframes
- The console deal ticket and fills table discounts applied 

## Specs
- 0083, 0084, 0085, 0086

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [x] Create new API to expose game metrics & discount factors for parties
- [x] Publish at the end of each epoch 

API to provide the following data:
- [x] Team ID
- [x] Number of epochs in team
- [x] Volume_discount_factor 
- [ ] Referral_discount_factor 
- [x] Referral_reward_factor (Not sure this is needed, only applies to referrer, and it would be on the referral set API right?)
- [x] Notional time weighted position (per asset)
- [x] Trade volume (party_epoch_notional_taker_volume)

Filtering requirements:
  - [x] Party ID
  - [x] Team ID
