### ISSUE TITLE
[Feature]: Enhance rewards API to support competitions

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9260]
# Feature Overview

**In order to** support front end 
**We will** enhance the rewards API
**So that** front end can build:
- The historic breakdown on the profile screen on page 11 of the wireframes
- The summary stats for the party on the profile screen on page 11 of the wireframes
- The actual rewards earned by each party in each game (where that game is individual)
- The rewards contributed to the team 

## Specs
- [Link](xyz) to spec or section within a spec

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] Rewards API to be enhanced to include the below:
  - [x] Game ID
  - [ ] If reward was earned via a team provide the Team ID 

Filterin requirements
  - [ ] Party ID (Should return all rewards earned by that party and be mandatory)
  - [ ] Team ID (Shoudl return all rewards earned by **that** party for the given team)
  - [ ] Epoch from / to
  - [ ] Game ID

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Current shape of rewards API 
<img width="1422" alt="image" src="https://github.com/vegaprotocol/vega/assets/89918817/a3b6f56f-3d7a-47f3-8b0f-4445c0285ebb">

**Comment by guoguojin** [comment]
Removed breaking change flag as the updated ticket no longer causes breaks.
