### ISSUE TITLE
[Feature]: Finalise referral set API (pt1)

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9261]
# Feature Overview

**In order to** support fron end 
**We will** ensure the new referral set API covers all the below
**So that** front end can build
- The referrer stats on page 10 of the wireframes (and in the miro that will soon exist [here](https://miro.com/app/board/uXjVOs_PBKk=/?share_link_id=783456245937))

## Specs
https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md#apis

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] Ensure the referral set API covers all of the things in the spec
  - [x] Team volume in last x days (referral_set_running_notional_taker_volume)
  - [x] Current tier (of the referrer)
  - [x] Total traders referred
  - [x] Total commission earned per asset per epoch
  - [x] Total discounts received by all referees per asset per epoch
  - [x] Members list
    - [x] Address
    - [x] Date joined (or number of epochs in team)

### Additional Details (optional)

Additional API updates to be completed in: https://github.com/vegaprotocol/vega/issues/9541
