### ISSUE TITLE
[Feature]: Finalise Teams API 

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9262]
# Feature Overview

**In order to** support front end
**We will** ensure the teams API covers all the below
**So that** front end can build 
- The team info on page 3 of the wireframes

## Specs
https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md#apis

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [ ] Ensure the teams API covers the following
  - [x] Name
  - [x] Team forum
  - [x] Team Logo
  - [x] Closed / open status
  - [x] Members list (sets referees)
  - [ ] Average rank (over the last N epochs - sortable - and handling for < N)
  - [x] Created At

Filtering requirements
  - [x] Team ID 

## Feature test scenarios
Detailed scenarios that can be executed as feature tests to verify that the feature has been implemented as expected.

GIVEN (setup/context) 
WHEN (action) 
THEN (assertion) For example...
See [here](https://github.com/vegaprotocol/vega/tree/develop/core/integration) for more format information and examples.

### Additional Details (optional)
Any additional information that provides context or gives information that will help us develop the feature.
