### ISSUE TITLE
[Feature]: Finalise referral set API (pt2)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#9541]
# Feature Overview

This is the second part of the front end request for referral set APIs: https://github.com/vegaprotocol/vega/issues/9261

**In order to** support front end 
**We will** ensure the new referral set API covers all the below
**So that** front end can build
- The referrer stats on page 10 of the wireframes (and in the miro that will soon exist [here](https://miro.com/app/board/uXjVOs_PBKk=/?share_link_id=783456245937))

## Specs
https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0083-RFPR-on_chain_referral_program.md#apis

## Tasks
A checklist of the tasks that are needed to develop the feature and meet the acceptance criteria and feature test scenarios.
- [x] Ensure the referral set API covers all of the remaining details in the spec
  - [x] Members list
    - [x] Total volume in last 30 days (in quantum presumably since that is what is going into the overall set calc)
    - [x] Commission earned from party in last 30 days (if possible)

**Comment by JonRay15** [comment]
Made a note  here that the volume will need to be quantum since that hadnt been explicitly specfied before.
