### ISSUE TITLE
Add MakerFees to FeeStats

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#9743]
Add new fee stats to the FeeStats events for maker fees, on every maker fees paid on a market.

Add to the FeeStats struct and event:
```
TotalMakerFeePaid map[string]*num.Uint
MakerFeeGenerated map[string]map[string]*num.Uint
```

Save in the database and serve through the API.

## Todo
- [x] Update the FeeStats state + snapshot  + publish with the event onEpochEnd
- [x] Add the fee to the stats in the following method: CalculateForContinuousMode
- [x] Update the database to store these new fields
- [x] Update gRPC + graphQL
