### ISSUE TITLE
Add support for zstd or 7z in place of zip for network history files

### ISSUE THREAD

**Issue by peterbarrow** [vegaprotocol/vega#9817]
The current implementation of network history relies on zip to compress each segment that is distributed around the network. Examining the compression ratio of the zipped files shows we can achieve a much smaller file if we use a more modern compression algorithm. 

Therefore we wish to look into upgrading the system to use either 7zip or zstd in place of zip.

This must be achieved in a backwards compatible way so that a new data node is able to read old segments compressed with zip as well as new segments compressed with the newer compressor. Users will be able to select their preferred api peers so that they only receive the data in the format they desire.

Part of this ticket is an investigation into which compressor is best in terms of CPU usage and compression ratio.

```[tasklist]
### Tasks
- [ ] Produce a report of compression ratio and CPU/memory usage for the different compressors and feed that back to core for review
- [ ] Add support in the data node to compress segments using the new algorithm
- [ ] Add support for the data node to load and handle the newly compressed segments
```

**Comment by ettec** [comment]
Tested a number of pure go compression algorithms using the attached go program (there are some out there that use CGo which I assume is a non-starter), results below.   

Summary is that the best compression algorithm is the 'zstd' lib, all other are either worse or within a few percent of what is currently done, however golang zstd implementation only gives a 15% improvement.  But the downside is that its not as well used and therefore tested as the stdlib compression and has an implementation which may be a bit overcomplex (see this issue for background-> https://github.com/golang/go/issues/62513).  In addition, a consumer of IPFS content has to assume the format of the content, there is no way of inferring this from the content id itself (which is just a hash of the content).  Thus to maintain backwards compatibility we would have to rewrap in a zip.   Basically the benefits here do not outweight the downsides IMO, so not worth it.

One other note, the compression level used by the Flate algo ( which backs Deflate, Flate, ZLib and GZip) could be increased to the best compression, but this results in only ~2%  percent difference, given this small improvement I think maintaining consistency in how we package the data across releases means it is not worth the candle.


Results:

Size of compressed_LZ4_Best_Compression.zip: 747316 bytes
Size of compressed_Store.zip: 2512972 bytes
Size of compressed_Deflate_default_compression.zip: 438272 bytes
Size of compressed_Flate_Best_Compression.zip: 425984 bytes
Size of compressed_ZLIB_Best_Compression.zip: 425984 bytes
Size of compressed_GZIP_Best_Compression.zip: 425984 bytes
Size of compressed_Klauspost_Native_ZSTD_Best_Compression.zip: 367349 bytes
Size of compressed_LZW_Best_Compression.zip: 1187840 bytes


Go program used to run the tests:

[relativecompression.zip](https://github.com/vegaprotocol/vega/files/13055810/relativecompression.zip)
