### ISSUE TITLE
Extend filters of transfer API

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#9883]
Add a new filter to the transfer API.

### todo
- [ ] add an onlyRewards boolean filter to the transfersConnection API
- [ ] if enabled returns only recurring and govRecurring transfers
- [ ] if enabled returns only transfers with a dispatch metric
