### ISSUE TITLE
Add filters to transfer list API

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#9981]
Now that we are using the transfer API with the isReward flag to give us our list of active rewards / games.

We need to be able to filter it for epoch periods so that we can show last 30 days or whatever time horizon we decide is appropriate in the front end.

We also need to be able to filter for entity scope team vs individual in case we have seperate leaderboards for these.

We also need to be able to see only active ones since dead ones are not much use.

https://docs.vega.xyz/mainnet/api/rest/data-v2/trading-data-service-list-transfers

## Tasks
- [x] Add from epoch / to epoch filter
- [ ] Add entiity scope (team / individual) filter
- [x] Add status filter
